In [182]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [183]:
df = pd.read_csv('test1_modify3.csv')
df

                  datetime  regular  casual  group
0      2017-01-01 00:00:00     63.0    13.0    1.0
1      2017-01-01 01:00:00     55.0    21.0    0.0
2      2017-01-01 02:00:00     38.0    19.0    0.0
3      2017-01-01 03:00:00     22.0    12.0    0.0
4      2017-01-01 04:00:00     16.0     7.0    0.0
...                    ...      ...     ...    ...
35346  2021-01-31 19:00:00   1346.0   531.0   13.0
35347  2021-01-31 20:00:00   1298.0   589.0    7.0
35348  2021-01-31 21:00:00   1229.0   594.0   13.0
35349  2021-01-31 22:00:00    750.0   283.0   10.0
35350  2021-01-31 23:00:00    496.0   192.0    6.0

[35351 rows x 4 columns]

### 관련있는 데이터 추가하기
- 우리가 하고자 하는 것이 자전거 이용량에 대한 것이므로 의미가 있는 데이터를 가져와야함
- e.g., 날씨에 따라 이용량에 영향이 있을 것이라고 판단
- e.g., 부동산의 가격에 따른 자전거 이용량은 영향 x
- 즉, 이용량 변화에 영향이 있을만한 정보를 가져올 수 있어야 함

In [184]:
import requests
import bs4

In [185]:
# url = 'https://freemeteo.co.uk/weather/seoul/history/daily-history/?gid=1835848&date=2017-01-01&station=10565&language=english&country=south-korea#google_vignette'
# table = pd.read_html(url)
# table

# df2 = table[6]
# df2

# df2['datetime'] = '2017-01-01' + ' ' + df2['Time'] + ':00'

# interested = ['datetime', 'Temperature', 'Rel. humidity', 'Dew Point', 'Wind']
# df3 = df2[interested]
# df3

# pd.merge(df4, df3, on='datetime', how='outer')

# df['date'] = df['datetime'].apply(lambda x: x.split(' ')[0])

# # 날짜 집합을 리스트로 변환하고 정렬
# sorted_dates = sorted(set(df['date']))
# sorted_dates

# for date in pd.range_date()
# 2023년 1월 1일부터 10일간의 일별 날짜 범위 생성
# date_range = pd.date_range(start='2023-01-01', periods=10, freq='D')
# 주요 매개변수:
# start: 시작 날짜
# end: 종료 날짜
# periods: 생성할 기간의 수
# freq: 날짜/시간 간격 (예: 'D'는 일별, 'M'은 월별)

In [186]:
# for date in sorted_dates:
#     url = f'https://freemeteo.co.uk/weather/seoul/history/daily-history/?gid=1835848&date={date}&station=10565&language=english&country=south-korea#google_vignette'
#     table = pd.read_html(url)
#     df_weather = table[6]
    
#     df_weather['datetime'] = f'{date}' + ' ' + df_weather['Time'] + ':00'
#     interested = ['datetime', 'Temperature', 'Rel. humidity', 'Dew Point', 'Wind']
#     df_date_weather = df_weather[interested]

#     pd.merge(df, df_date_weather, on='datetime', how='outer')

In [187]:
# df_weather = pd.DataFrame()

# for date in sorted_dates:
#     url = f'https://freemeteo.co.uk/weather/seoul/history/daily-history/?gid=1835848&date={date}&station=10565&language=english&country=south-korea#google_vignette'
#     tables = pd.read_html(url)
#     time.sleep(1)
    
#     # table[6]의 데이터를 임시 데이터프레임에 저장
#     temp_df = tables[6]
    
#     # datetime 생성
#     temp_df['datetime'] = f'{date}' + ' ' + temp_df['Time'] + ':00'

#     # 컬럼 추출
#     interested = ['datetime', 'Temperature', 'Rel. humidity', 'Dew Point', 'Wind']
#     temp_weather_df = temp_df[interested]
    
#     # 기존 df_weather에 새 데이터 추가
#     df_weather = pd.concat([df_weather, temp_weather_df], ignore_index=True)

#     # df에 df_weather outer
#     pd.merge(df, df_weather, on='datetime', how='outer')
    
#     print(df_weather.shape)
    
# # 결과 확인
# df_weather

# # 가져오는 개수가 다른 이유 -> 기상 데이터가 없는 것들도 존재+시간대가 00시로만 끝나지 않음 09:21 이런식으로 존재

In [188]:
from glob import glob

In [189]:
file_path = 'C:/Users/twas0/test/weather/'
all_path = glob(file_path + '*.csv')
all_path

['C:/Users/twas0/test/weather\\2017-01-01.csv',
 'C:/Users/twas0/test/weather\\2017-01-02.csv',
 'C:/Users/twas0/test/weather\\2017-01-03.csv',
 'C:/Users/twas0/test/weather\\2017-01-04.csv',
 'C:/Users/twas0/test/weather\\2017-01-05.csv',
 'C:/Users/twas0/test/weather\\2017-01-06.csv',
 'C:/Users/twas0/test/weather\\2017-01-07.csv',
 'C:/Users/twas0/test/weather\\2017-01-08.csv',
 'C:/Users/twas0/test/weather\\2017-01-09.csv',
 'C:/Users/twas0/test/weather\\2017-01-10.csv',
 'C:/Users/twas0/test/weather\\2017-01-11.csv',
 'C:/Users/twas0/test/weather\\2017-01-12.csv',
 'C:/Users/twas0/test/weather\\2017-01-13.csv',
 'C:/Users/twas0/test/weather\\2017-01-14.csv',
 'C:/Users/twas0/test/weather\\2017-01-15.csv',
 'C:/Users/twas0/test/weather\\2017-01-16.csv',
 'C:/Users/twas0/test/weather\\2017-01-17.csv',
 'C:/Users/twas0/test/weather\\2017-01-18.csv',
 'C:/Users/twas0/test/weather\\2017-01-19.csv',
 'C:/Users/twas0/test/weather\\2017-01-20.csv',
 'C:/Users/twas0/test/weather\\2017-01-21.csv',
 'C:/Users/twas0/test/weather\\2017-01-22.csv',
 'C:/Users/twas0/test/weather\\2017-01-23.csv',
 'C:/Users/twas0/test/weather\\2017-01-24.csv',
 'C:/Users/twas0/test/weather\\2017-01-25.csv',
 'C:/Users/twas0/test/weather\\2017-01-26.csv',
 'C:/Users/twas0/test/weather\\2017-01-27.csv',
 'C:/Users/twas0/test/weather\\2017-01-28.csv',
 'C:/Users/twas0/test/weather\\2017-01-29.csv',
 'C:/Users/twas0/test/weather\\2017-01-30.csv',
 'C:/Users/twas0/test/weather\\2017-01-31.csv',
 'C:/Users/twas0/test/weather\\2017-02-01.csv',
 'C:/Users/twas0/test/weather\\2017-02-02.csv',
 'C:/Users/twas0/test/weather\\2017-02-03.csv',
 'C:/Users/twas0/test/weather\\2017-02-04.csv',
 'C:/Users/twas0/test/weather\\2017-02-05.csv',
 'C:/Users/twas0/test/weather\\2017-02-06.csv',
 'C:/Users/twas0/test/weather\\2017-02-07.csv',
 'C:/Users/twas0/test/weather\\2017-02-08.csv',
 'C:/Users/twas0/test/weather\\2017-02-09.csv',
 'C:/Users/twas0/test/weather\\2017-02-10.csv',
 'C:/Users/twas0/test/weather\\2017-02-11.csv',
 'C:/Users/twas0/test/weather\\2017-02-12.csv',
 'C:/Users/twas0/test/weather\\2017-02-13.csv',
 'C:/Users/twas0/test/weather\\2017-02-14.csv',
 'C:/Users/twas0/test/weather\\2017-02-15.csv',
 'C:/Users/twas0/test/weather\\2017-02-16.csv',
 'C:/Users/twas0/test/weather\\2017-02-17.csv',
 'C:/Users/twas0/test/weather\\2017-02-18.csv',
 'C:/Users/twas0/test/weather\\2017-02-19.csv',
 'C:/Users/twas0/test/weather\\2017-02-20.csv',
 'C:/Users/twas0/test/weather\\2017-02-21.csv',
 'C:/Users/twas0/test/weather\\2017-02-22.csv',
 'C:/Users/twas0/test/weather\\2017-02-23.csv',
 'C:/Users/twas0/test/weather\\2017-02-24.csv',
 'C:/Users/twas0/test/weather\\2017-02-25.csv',
 'C:/Users/twas0/test/weather\\2017-02-26.csv',
 'C:/Users/twas0/test/weather\\2017-02-27.csv',
 'C:/Users/twas0/test/weather\\2017-02-28.csv',
 'C:/Users/twas0/test/weather\\2017-03-01.csv',
 'C:/Users/twas0/test/weather\\2017-03-02.csv',
 'C:/Users/twas0/test/weather\\2017-03-03.csv',
 'C:/Users/twas0/test/weather\\2017-03-04.csv',
 'C:/Users/twas0/test/weather\\2017-03-05.csv',
 'C:/Users/twas0/test/weather\\2017-03-06.csv',
 'C:/Users/twas0/test/weather\\2017-03-07.csv',
 'C:/Users/twas0/test/weather\\2017-03-08.csv',
 'C:/Users/twas0/test/weather\\2017-03-09.csv',
 'C:/Users/twas0/test/weather\\2017-03-10.csv',
 'C:/Users/twas0/test/weather\\2017-03-11.csv',
 'C:/Users/twas0/test/weather\\2017-03-12.csv',
 'C:/Users/twas0/test/weather\\2017-03-13.csv',
 'C:/Users/twas0/test/weather\\2017-03-14.csv',
 'C:/Users/twas0/test/weather\\2017-03-15.csv',
 'C:/Users/twas0/test/weather\\2017-03-16.csv',
 'C:/Users/twas0/test/weather\\2017-03-17.csv',
 'C:/Users/twas0/test/weather\\2017-03-18.csv',
 'C:/Users/twas0/test/weather\\2017-03-19.csv',
 'C:/Users/twas0/test/weather\\2017-03-20.csv',
 'C:/Users/twas0/test/weather\\2017-03-21.csv',
 'C:/Users/twas0/test/weather\\2017-03-22.csv',
 'C:/Users/twas0/test/weather\\2017-03-23.csv',
 'C:/Users/twas0/test/weather\\2017-03-24.csv',
 'C:/Users/twas0/test/weather\\2017-03-25.csv',
 'C:/Users/twas0/test/weather\\2017-03-26.csv',
 'C:/Users/twas0/test/weather\\2017-03-27.csv',
 'C:/Users/twas0/test/weather\\2017-03-28.csv',
 'C:/Users/twas0/test/weather\\2017-03-29.csv',
 'C:/Users/twas0/test/weather\\2017-03-30.csv',
 'C:/Users/twas0/test/weather\\2017-03-31.csv',
 'C:/Users/twas0/test/weather\\2017-04-01.csv',
 'C:/Users/twas0/test/weather\\2017-04-02.csv',
 'C:/Users/twas0/test/weather\\2017-04-03.csv',
 'C:/Users/twas0/test/weather\\2017-04-04.csv',
 'C:/Users/twas0/test/weather\\2017-04-05.csv',
 'C:/Users/twas0/test/weather\\2017-04-06.csv',
 'C:/Users/twas0/test/weather\\2017-04-07.csv',
 'C:/Users/twas0/test/weather\\2017-04-08.csv',
 'C:/Users/twas0/test/weather\\2017-04-09.csv',
 'C:/Users/twas0/test/weather\\2017-04-10.csv',
 'C:/Users/twas0/test/weather\\2017-04-11.csv',
 'C:/Users/twas0/test/weather\\2017-04-12.csv',
 'C:/Users/twas0/test/weather\\2017-04-13.csv',
 'C:/Users/twas0/test/weather\\2017-04-14.csv',
 'C:/Users/twas0/test/weather\\2017-04-15.csv',
 'C:/Users/twas0/test/weather\\2017-04-16.csv',
 'C:/Users/twas0/test/weather\\2017-04-17.csv',
 'C:/Users/twas0/test/weather\\2017-04-18.csv',
 'C:/Users/twas0/test/weather\\2017-04-19.csv',
 'C:/Users/twas0/test/weather\\2017-04-20.csv',
 'C:/Users/twas0/test/weather\\2017-04-21.csv',
 'C:/Users/twas0/test/weather\\2017-04-22.csv',
 'C:/Users/twas0/test/weather\\2017-04-23.csv',
 'C:/Users/twas0/test/weather\\2017-04-24.csv',
 'C:/Users/twas0/test/weather\\2017-04-25.csv',
 'C:/Users/twas0/test/weather\\2017-04-26.csv',
 'C:/Users/twas0/test/weather\\2017-04-27.csv',
 'C:/Users/twas0/test/weather\\2017-04-28.csv',
 'C:/Users/twas0/test/weather\\2017-04-29.csv',
 'C:/Users/twas0/test/weather\\2017-04-30.csv',
 'C:/Users/twas0/test/weather\\2017-05-01.csv',
 'C:/Users/twas0/test/weather\\2017-05-02.csv',
 'C:/Users/twas0/test/weather\\2017-05-03.csv',
 'C:/Users/twas0/test/weather\\2017-05-04.csv',
 'C:/Users/twas0/test/weather\\2017-05-05.csv',
 'C:/Users/twas0/test/weather\\2017-05-06.csv',
 'C:/Users/twas0/test/weather\\2017-05-07.csv',
 'C:/Users/twas0/test/weather\\2017-05-08.csv',
 'C:/Users/twas0/test/weather\\2017-05-09.csv',
 'C:/Users/twas0/test/weather\\2017-05-10.csv',
 'C:/Users/twas0/test/weather\\2017-05-11.csv',
 'C:/Users/twas0/test/weather\\2017-05-12.csv',
 'C:/Users/twas0/test/weather\\2017-05-13.csv',
 'C:/Users/twas0/test/weather\\2017-05-14.csv',
 'C:/Users/twas0/test/weather\\2017-05-15.csv',
 'C:/Users/twas0/test/weather\\2017-05-16.csv',
 'C:/Users/twas0/test/weather\\2017-05-17.csv',
 'C:/Users/twas0/test/weather\\2017-05-18.csv',
 'C:/Users/twas0/test/weather\\2017-05-19.csv',
 'C:/Users/twas0/test/weather\\2017-05-20.csv',
 'C:/Users/twas0/test/weather\\2017-05-21.csv',
 'C:/Users/twas0/test/weather\\2017-05-22.csv',
 'C:/Users/twas0/test/weather\\2017-05-23.csv',
 'C:/Users/twas0/test/weather\\2017-05-24.csv',
 'C:/Users/twas0/test/weather\\2017-05-25.csv',
 'C:/Users/twas0/test/weather\\2017-05-26.csv',
 'C:/Users/twas0/test/weather\\2017-05-27.csv',
 'C:/Users/twas0/test/weather\\2017-05-28.csv',
 'C:/Users/twas0/test/weather\\2017-05-29.csv',
 'C:/Users/twas0/test/weather\\2017-05-30.csv',
 'C:/Users/twas0/test/weather\\2017-05-31.csv',
 'C:/Users/twas0/test/weather\\2017-06-01.csv',
 'C:/Users/twas0/test/weather\\2017-06-02.csv',
 'C:/Users/twas0/test/weather\\2017-06-03.csv',
 'C:/Users/twas0/test/weather\\2017-06-04.csv',
 'C:/Users/twas0/test/weather\\2017-06-05.csv',
 'C:/Users/twas0/test/weather\\2017-06-06.csv',
 'C:/Users/twas0/test/weather\\2017-06-07.csv',
 'C:/Users/twas0/test/weather\\2017-06-08.csv',
 'C:/Users/twas0/test/weather\\2017-06-09.csv',
 'C:/Users/twas0/test/weather\\2017-06-10.csv',
 'C:/Users/twas0/test/weather\\2017-06-11.csv',
 'C:/Users/twas0/test/weather\\2017-06-12.csv',
 'C:/Users/twas0/test/weather\\2017-06-13.csv',
 'C:/Users/twas0/test/weather\\2017-06-14.csv',
 'C:/Users/twas0/test/weather\\2017-06-15.csv',
 'C:/Users/twas0/test/weather\\2017-06-16.csv',
 'C:/Users/twas0/test/weather\\2017-06-17.csv',
 'C:/Users/twas0/test/weather\\2017-06-18.csv',
 'C:/Users/twas0/test/weather\\2017-06-19.csv',
 'C:/Users/twas0/test/weather\\2017-06-20.csv',
 'C:/Users/twas0/test/weather\\2017-06-21.csv',
 'C:/Users/twas0/test/weather\\2017-06-22.csv',
 'C:/Users/twas0/test/weather\\2017-06-23.csv',
 'C:/Users/twas0/test/weather\\2017-06-24.csv',
 'C:/Users/twas0/test/weather\\2017-06-25.csv',
 'C:/Users/twas0/test/weather\\2017-06-26.csv',
 'C:/Users/twas0/test/weather\\2017-06-27.csv',
 'C:/Users/twas0/test/weather\\2017-06-28.csv',
 'C:/Users/twas0/test/weather\\2017-06-29.csv',
 'C:/Users/twas0/test/weather\\2017-06-30.csv',
 'C:/Users/twas0/test/weather\\2017-07-01.csv',
 'C:/Users/twas0/test/weather\\2017-07-02.csv',
 'C:/Users/twas0/test/weather\\2017-07-03.csv',
 'C:/Users/twas0/test/weather\\2017-07-04.csv',
 'C:/Users/twas0/test/weather\\2017-07-05.csv',
 'C:/Users/twas0/test/weather\\2017-07-06.csv',
 'C:/Users/twas0/test/weather\\2017-07-07.csv',
 'C:/Users/twas0/test/weather\\2017-07-08.csv',
 'C:/Users/twas0/test/weather\\2017-07-09.csv',
 'C:/Users/twas0/test/weather\\2017-07-10.csv',
 'C:/Users/twas0/test/weather\\2017-07-11.csv',
 'C:/Users/twas0/test/weather\\2017-07-12.csv',
 'C:/Users/twas0/test/weather\\2017-07-13.csv',
 'C:/Users/twas0/test/weather\\2017-07-14.csv',
 'C:/Users/twas0/test/weather\\2017-07-15.csv',
 'C:/Users/twas0/test/weather\\2017-07-16.csv',
 'C:/Users/twas0/test/weather\\2017-07-17.csv',
 'C:/Users/twas0/test/weather\\2017-07-18.csv',
 'C:/Users/twas0/test/weather\\2017-07-19.csv',
 'C:/Users/twas0/test/weather\\2017-07-20.csv',
 'C:/Users/twas0/test/weather\\2017-07-21.csv',
 'C:/Users/twas0/test/weather\\2017-07-22.csv',
 'C:/Users/twas0/test/weather\\2017-07-23.csv',
 'C:/Users/twas0/test/weather\\2017-07-24.csv',
 'C:/Users/twas0/test/weather\\2017-07-25.csv',
 'C:/Users/twas0/test/weather\\2017-07-26.csv',
 'C:/Users/twas0/test/weather\\2017-07-27.csv',
 'C:/Users/twas0/test/weather\\2017-07-28.csv',
 'C:/Users/twas0/test/weather\\2017-07-29.csv',
 'C:/Users/twas0/test/weather\\2017-07-30.csv',
 'C:/Users/twas0/test/weather\\2017-07-31.csv',
 'C:/Users/twas0/test/weather\\2017-08-01.csv',
 'C:/Users/twas0/test/weather\\2017-08-02.csv',
 'C:/Users/twas0/test/weather\\2017-08-03.csv',
 'C:/Users/twas0/test/weather\\2017-08-04.csv',
 'C:/Users/twas0/test/weather\\2017-08-05.csv',
 'C:/Users/twas0/test/weather\\2017-08-06.csv',
 'C:/Users/twas0/test/weather\\2017-08-07.csv',
 'C:/Users/twas0/test/weather\\2017-08-08.csv',
 'C:/Users/twas0/test/weather\\2017-08-09.csv',
 'C:/Users/twas0/test/weather\\2017-08-10.csv',
 'C:/Users/twas0/test/weather\\2017-08-11.csv',
 'C:/Users/twas0/test/weather\\2017-08-12.csv',
 'C:/Users/twas0/test/weather\\2017-08-13.csv',
 'C:/Users/twas0/test/weather\\2017-08-14.csv',
 'C:/Users/twas0/test/weather\\2017-08-15.csv',
 'C:/Users/twas0/test/weather\\2017-08-16.csv',
 'C:/Users/twas0/test/weather\\2017-08-17.csv',
 'C:/Users/twas0/test/weather\\2017-08-18.csv',
 'C:/Users/twas0/test/weather\\2017-08-19.csv',
 'C:/Users/twas0/test/weather\\2017-08-20.csv',
 'C:/Users/twas0/test/weather\\2017-08-21.csv',
 'C:/Users/twas0/test/weather\\2017-08-22.csv',
 'C:/Users/twas0/test/weather\\2017-08-23.csv',
 'C:/Users/twas0/test/weather\\2017-08-24.csv',
 'C:/Users/twas0/test/weather\\2017-08-25.csv',
 'C:/Users/twas0/test/weather\\2017-08-26.csv',
 'C:/Users/twas0/test/weather\\2017-08-27.csv',
 'C:/Users/twas0/test/weather\\2017-08-28.csv',
 'C:/Users/twas0/test/weather\\2017-08-29.csv',
 'C:/Users/twas0/test/weather\\2017-08-30.csv',
 'C:/Users/twas0/test/weather\\2017-08-31.csv',
 'C:/Users/twas0/test/weather\\2017-09-01.csv',
 'C:/Users/twas0/test/weather\\2017-09-02.csv',
 'C:/Users/twas0/test/weather\\2017-09-03.csv',
 'C:/Users/twas0/test/weather\\2017-09-04.csv',
 'C:/Users/twas0/test/weather\\2017-09-05.csv',
 'C:/Users/twas0/test/weather\\2017-09-06.csv',
 'C:/Users/twas0/test/weather\\2017-09-07.csv',
 'C:/Users/twas0/test/weather\\2017-09-08.csv',
 'C:/Users/twas0/test/weather\\2017-09-09.csv',
 'C:/Users/twas0/test/weather\\2017-09-10.csv',
 'C:/Users/twas0/test/weather\\2017-09-11.csv',
 'C:/Users/twas0/test/weather\\2017-09-12.csv',
 'C:/Users/twas0/test/weather\\2017-09-13.csv',
 'C:/Users/twas0/test/weather\\2017-09-14.csv',
 'C:/Users/twas0/test/weather\\2017-09-15.csv',
 'C:/Users/twas0/test/weather\\2017-09-16.csv',
 'C:/Users/twas0/test/weather\\2017-09-17.csv',
 'C:/Users/twas0/test/weather\\2017-09-18.csv',
 'C:/Users/twas0/test/weather\\2017-09-19.csv',
 'C:/Users/twas0/test/weather\\2017-09-20.csv',
 'C:/Users/twas0/test/weather\\2017-09-21.csv',
 'C:/Users/twas0/test/weather\\2017-09-22.csv',
 'C:/Users/twas0/test/weather\\2017-09-23.csv',
 'C:/Users/twas0/test/weather\\2017-09-24.csv',
 'C:/Users/twas0/test/weather\\2017-09-25.csv',
 'C:/Users/twas0/test/weather\\2017-09-26.csv',
 'C:/Users/twas0/test/weather\\2017-09-27.csv',
 'C:/Users/twas0/test/weather\\2017-09-28.csv',
 'C:/Users/twas0/test/weather\\2017-09-29.csv',
 'C:/Users/twas0/test/weather\\2017-09-30.csv',
 'C:/Users/twas0/test/weather\\2017-10-01.csv',
 'C:/Users/twas0/test/weather\\2017-10-02.csv',
 'C:/Users/twas0/test/weather\\2017-10-03.csv',
 'C:/Users/twas0/test/weather\\2017-10-04.csv',
 'C:/Users/twas0/test/weather\\2017-10-05.csv',
 'C:/Users/twas0/test/weather\\2017-10-06.csv',
 'C:/Users/twas0/test/weather\\2017-10-07.csv',
 'C:/Users/twas0/test/weather\\2017-10-08.csv',
 'C:/Users/twas0/test/weather\\2017-10-09.csv',
 'C:/Users/twas0/test/weather\\2017-10-10.csv',
 'C:/Users/twas0/test/weather\\2017-10-11.csv',
 'C:/Users/twas0/test/weather\\2017-10-12.csv',
 'C:/Users/twas0/test/weather\\2017-10-13.csv',
 'C:/Users/twas0/test/weather\\2017-10-14.csv',
 'C:/Users/twas0/test/weather\\2017-10-15.csv',
 'C:/Users/twas0/test/weather\\2017-10-16.csv',
 'C:/Users/twas0/test/weather\\2017-10-17.csv',
 'C:/Users/twas0/test/weather\\2017-10-18.csv',
 'C:/Users/twas0/test/weather\\2017-10-19.csv',
 'C:/Users/twas0/test/weather\\2017-10-20.csv',
 'C:/Users/twas0/test/weather\\2017-10-21.csv',
 'C:/Users/twas0/test/weather\\2017-10-22.csv',
 'C:/Users/twas0/test/weather\\2017-10-23.csv',
 'C:/Users/twas0/test/weather\\2017-10-24.csv',
 'C:/Users/twas0/test/weather\\2017-10-25.csv',
 'C:/Users/twas0/test/weather\\2017-10-26.csv',
 'C:/Users/twas0/test/weather\\2017-10-27.csv',
 'C:/Users/twas0/test/weather\\2017-10-28.csv',
 'C:/Users/twas0/test/weather\\2017-10-29.csv',
 'C:/Users/twas0/test/weather\\2017-10-30.csv',
 'C:/Users/twas0/test/weather\\2017-10-31.csv',
 'C:/Users/twas0/test/weather\\2017-11-01.csv',
 'C:/Users/twas0/test/weather\\2017-11-02.csv',
 'C:/Users/twas0/test/weather\\2017-11-03.csv',
 'C:/Users/twas0/test/weather\\2017-11-04.csv',
 'C:/Users/twas0/test/weather\\2017-11-05.csv',
 'C:/Users/twas0/test/weather\\2017-11-06.csv',
 'C:/Users/twas0/test/weather\\2017-11-07.csv',
 'C:/Users/twas0/test/weather\\2017-11-08.csv',
 'C:/Users/twas0/test/weather\\2017-11-09.csv',
 'C:/Users/twas0/test/weather\\2017-11-10.csv',
 'C:/Users/twas0/test/weather\\2017-11-11.csv',
 'C:/Users/twas0/test/weather\\2017-11-12.csv',
 'C:/Users/twas0/test/weather\\2017-11-13.csv',
 'C:/Users/twas0/test/weather\\2017-11-14.csv',
 'C:/Users/twas0/test/weather\\2017-11-15.csv',
 'C:/Users/twas0/test/weather\\2017-11-16.csv',
 'C:/Users/twas0/test/weather\\2017-11-17.csv',
 'C:/Users/twas0/test/weather\\2017-11-18.csv',
 'C:/Users/twas0/test/weather\\2017-11-19.csv',
 'C:/Users/twas0/test/weather\\2017-11-20.csv',
 'C:/Users/twas0/test/weather\\2017-11-21.csv',
 'C:/Users/twas0/test/weather\\2017-11-22.csv',
 'C:/Users/twas0/test/weather\\2017-11-23.csv',
 'C:/Users/twas0/test/weather\\2017-11-24.csv',
 'C:/Users/twas0/test/weather\\2017-11-25.csv',
 'C:/Users/twas0/test/weather\\2017-11-26.csv',
 'C:/Users/twas0/test/weather\\2017-11-27.csv',
 'C:/Users/twas0/test/weather\\2017-11-28.csv',
 'C:/Users/twas0/test/weather\\2017-11-29.csv',
 'C:/Users/twas0/test/weather\\2017-11-30.csv',
 'C:/Users/twas0/test/weather\\2017-12-01.csv',
 'C:/Users/twas0/test/weather\\2017-12-02.csv',
 'C:/Users/twas0/test/weather\\2017-12-03.csv',
 'C:/Users/twas0/test/weather\\2017-12-04.csv',
 'C:/Users/twas0/test/weather\\2017-12-05.csv',
 'C:/Users/twas0/test/weather\\2017-12-06.csv',
 'C:/Users/twas0/test/weather\\2017-12-07.csv',
 'C:/Users/twas0/test/weather\\2017-12-08.csv',
 'C:/Users/twas0/test/weather\\2017-12-09.csv',
 'C:/Users/twas0/test/weather\\2017-12-10.csv',
 'C:/Users/twas0/test/weather\\2017-12-11.csv',
 'C:/Users/twas0/test/weather\\2017-12-12.csv',
 'C:/Users/twas0/test/weather\\2017-12-13.csv',
 'C:/Users/twas0/test/weather\\2017-12-14.csv',
 'C:/Users/twas0/test/weather\\2017-12-15.csv',
 'C:/Users/twas0/test/weather\\2017-12-16.csv',
 'C:/Users/twas0/test/weather\\2017-12-17.csv',
 'C:/Users/twas0/test/weather\\2017-12-18.csv',
 'C:/Users/twas0/test/weather\\2017-12-19.csv',
 'C:/Users/twas0/test/weather\\2017-12-20.csv',
 'C:/Users/twas0/test/weather\\2017-12-21.csv',
 'C:/Users/twas0/test/weather\\2017-12-22.csv',
 'C:/Users/twas0/test/weather\\2017-12-23.csv',
 'C:/Users/twas0/test/weather\\2017-12-24.csv',
 'C:/Users/twas0/test/weather\\2017-12-25.csv',
 'C:/Users/twas0/test/weather\\2017-12-26.csv',
 'C:/Users/twas0/test/weather\\2017-12-27.csv',
 'C:/Users/twas0/test/weather\\2017-12-28.csv',
 'C:/Users/twas0/test/weather\\2017-12-29.csv',
 'C:/Users/twas0/test/weather\\2017-12-30.csv',
 'C:/Users/twas0/test/weather\\2017-12-31.csv',
 'C:/Users/twas0/test/weather\\2018-01-01.csv',
 'C:/Users/twas0/test/weather\\2018-01-02.csv',
 'C:/Users/twas0/test/weather\\2018-01-03.csv',
 'C:/Users/twas0/test/weather\\2018-01-04.csv',
 'C:/Users/twas0/test/weather\\2018-01-05.csv',
 'C:/Users/twas0/test/weather\\2018-01-06.csv',
 'C:/Users/twas0/test/weather\\2018-01-07.csv',
 'C:/Users/twas0/test/weather\\2018-01-08.csv',
 'C:/Users/twas0/test/weather\\2018-01-09.csv',
 'C:/Users/twas0/test/weather\\2018-01-10.csv',
 'C:/Users/twas0/test/weather\\2018-01-11.csv',
 'C:/Users/twas0/test/weather\\2018-01-12.csv',
 'C:/Users/twas0/test/weather\\2018-01-13.csv',
 'C:/Users/twas0/test/weather\\2018-01-14.csv',
 'C:/Users/twas0/test/weather\\2018-01-15.csv',
 'C:/Users/twas0/test/weather\\2018-01-16.csv',
 'C:/Users/twas0/test/weather\\2018-01-17.csv',
 'C:/Users/twas0/test/weather\\2018-01-18.csv',
 'C:/Users/twas0/test/weather\\2018-01-19.csv',
 'C:/Users/twas0/test/weather\\2018-01-20.csv',
 'C:/Users/twas0/test/weather\\2018-01-21.csv',
 'C:/Users/twas0/test/weather\\2018-01-22.csv',
 'C:/Users/twas0/test/weather\\2018-01-23.csv',
 'C:/Users/twas0/test/weather\\2018-01-24.csv',
 'C:/Users/twas0/test/weather\\2018-01-25.csv',
 'C:/Users/twas0/test/weather\\2018-01-26.csv',
 'C:/Users/twas0/test/weather\\2018-01-27.csv',
 'C:/Users/twas0/test/weather\\2018-01-28.csv',
 'C:/Users/twas0/test/weather\\2018-01-29.csv',
 'C:/Users/twas0/test/weather\\2018-01-30.csv',
 'C:/Users/twas0/test/weather\\2018-01-31.csv',
 'C:/Users/twas0/test/weather\\2018-02-01.csv',
 'C:/Users/twas0/test/weather\\2018-02-02.csv',
 'C:/Users/twas0/test/weather\\2018-02-03.csv',
 'C:/Users/twas0/test/weather\\2018-02-04.csv',
 'C:/Users/twas0/test/weather\\2018-02-05.csv',
 'C:/Users/twas0/test/weather\\2018-02-06.csv',
 'C:/Users/twas0/test/weather\\2018-02-07.csv',
 'C:/Users/twas0/test/weather\\2018-02-08.csv',
 'C:/Users/twas0/test/weather\\2018-02-09.csv',
 'C:/Users/twas0/test/weather\\2018-02-10.csv',
 'C:/Users/twas0/test/weather\\2018-02-11.csv',
 'C:/Users/twas0/test/weather\\2018-02-12.csv',
 'C:/Users/twas0/test/weather\\2018-02-13.csv',
 'C:/Users/twas0/test/weather\\2018-02-14.csv',
 'C:/Users/twas0/test/weather\\2018-02-15.csv',
 'C:/Users/twas0/test/weather\\2018-02-16.csv',
 'C:/Users/twas0/test/weather\\2018-02-17.csv',
 'C:/Users/twas0/test/weather\\2018-02-18.csv',
 'C:/Users/twas0/test/weather\\2018-02-19.csv',
 'C:/Users/twas0/test/weather\\2018-02-20.csv',

In [190]:
all_cols = []

for path in all_path:
    cols = list(pd.read_csv(path, encoding='cp949', skiprows=lambda x: x>2).columns) # 3이상의 로우(행)는 생략해줘
    all_cols = all_cols + cols

set(all_cols)

{'DescriptionDetails',
 'Dew Point',
 'Icon',
 'Pressure',
 'Rel. humidity',
 'Relative Temperature',
 'Temperature',
 'Time',
 'Wind',
 'Wind Gust',
 'date'}

In [191]:
interested = ['Time','Temperature', 'Rel. humidity', 'Dew Point', 'Wind', 'date']

all_df = pd.DataFrame()
for path in all_path:
    single = pd.read_csv(path, encoding='utf-8')
    
    all_df = pd.concat([all_df, single[interested]])
    print(all_df.shape)
    
    del single # 기존에 있던 single을 삭제해야 이어붙일때 기존 데이터를 안가져옴

(24, 6)
(50, 6)
(76, 6)
(101, 6)
(125, 6)
(149, 6)
(174, 6)
(198, 6)
(223, 6)
(247, 6)
(271, 6)
(295, 6)
(321, 6)
(345, 6)
(369, 6)
(393, 6)
(394, 6)
(394, 6)
(394, 6)
(394, 6)
(394, 6)
(394, 6)
(394, 6)
(394, 6)
(394, 6)
(402, 6)
(428, 6)
(452, 6)
(481, 6)
(507, 6)
(531, 6)
(555, 6)
(579, 6)
(605, 6)
(631, 6)
(656, 6)
(680, 6)
(704, 6)
(728, 6)
(752, 6)
(776, 6)
(800, 6)
(824, 6)
(848, 6)
(872, 6)
(896, 6)
(921, 6)
(946, 6)
(970, 6)
(994, 6)
(1019, 6)
(1043, 6)
(1071, 6)
(1095, 6)
(1119, 6)
(1147, 6)
(1173, 6)
(1197, 6)
(1221, 6)
(1246, 6)
(1270, 6)
(1294, 6)
(1319, 6)
(1349, 6)
(1373, 6)
(1397, 6)
(1422, 6)
(1446, 6)
(1470, 6)
(1494, 6)
(1519, 6)
(1543, 6)
(1567, 6)
(1591, 6)
(1615, 6)
(1639, 6)
(1664, 6)
(1691, 6)
(1716, 6)
(1742, 6)
(1766, 6)
(1790, 6)
(1814, 6)
(1838, 6)
(1862, 6)
(1886, 6)
(1913, 6)
(1937, 6)
(1961, 6)
(1985, 6)
(2010, 6)
(2035, 6)
(2060, 6)
(2084, 6)
(2112, 6)
(2138, 6)
(2162, 6)
(2189, 6)
(2217, 6)
(2241, 6)
(2265, 6)
(2289, 6)
(2313, 6)
(2340, 6)
(2364, 6)
(2388, 6)
(2413, 6)
(2442, 6)
(2448, 6)
(2474, 6)
(2498, 6)
(2525, 6)
(2549, 6)
(2573, 6)
(2597, 6)
(2621, 6)
(2645, 6)
(2670, 6)
(2694, 6)
(2718, 6)
(2744, 6)
(2768, 6)
(2792, 6)
(2816, 6)
(2840, 6)
(2864, 6)
(2888, 6)
(2912, 6)
(2937, 6)
(2964, 6)
(2988, 6)
(3012, 6)
(3043, 6)
(3067, 6)
(3091, 6)
(3115, 6)
(3139, 6)
(3163, 6)
(3187, 6)
(3211, 6)
(3235, 6)
(3259, 6)
(3288, 6)
(3312, 6)
(3336, 6)
(3360, 6)
(3384, 6)
(3408, 6)
(3432, 6)
(3456, 6)
(3480, 6)
(3506, 6)
(3530, 6)
(3554, 6)
(3578, 6)
(3602, 6)
(3628, 6)
(3654, 6)
(3678, 6)
(3702, 6)
(3729, 6)
(3753, 6)
(3777, 6)
(3801, 6)
(3825, 6)
(3849, 6)
(3874, 6)
(3898, 6)
(3922, 6)
(3947, 6)
(3971, 6)
(3995, 6)
(4019, 6)
(4043, 6)
(4067, 6)
(4091, 6)
(4120, 6)
(4145, 6)
(4169, 6)
(4195, 6)
(4220, 6)
(4247, 6)
(4287, 6)
(4318, 6)
(4346, 6)
(4371, 6)
(4395, 6)
(4430, 6)
(4454, 6)
(4483, 6)
(4523, 6)
(4548, 6)
(4572, 6)
(4597, 6)
(4624, 6)
(4652, 6)
(4678, 6)
(4706, 6)
(4731, 6)
(4755, 6)
(4779, 6)
(4803, 6)
(4828, 6)
(4863, 6)
(4892, 6)
(4917, 6)
(4941, 6)
(4966, 6)
(4992, 6)
(5016, 6)
(5040, 6)
(5069, 6)
(5093, 6)
(5117, 6)
(5141, 6)
(5165, 6)
(5189, 6)
(5215, 6)
(5239, 6)
(5263, 6)
(5287, 6)
(5312, 6)
(5336, 6)
(5360, 6)
(5384, 6)
(5410, 6)
(5442, 6)
(5468, 6)
(5493, 6)
(5518, 6)
(5542, 6)
(5573, 6)
(5600, 6)
(5614, 6)
(5630, 6)
(5660, 6)
(5684, 6)
(5708, 6)
(5732, 6)
(5757, 6)
(5781, 6)
(5805, 6)
(5831, 6)
(5855, 6)
(5879, 6)
(5903, 6)
(5927, 6)
(5951, 6)
(5975, 6)
(5999, 6)
(6027, 6)
(6055, 6)
(6079, 6)
(6103, 6)
(6127, 6)
(6151, 6)
(6175, 6)
(6199, 6)
(6223, 6)
(6247, 6)
(6271, 6)
(6298, 6)
(6322, 6)
(6346, 6)
(6370, 6)
(6394, 6)
(6419, 6)
(6443, 6)
(6467, 6)
(6492, 6)
(6516, 6)
(6540, 6)
(6564, 6)
(6589, 6)
(6613, 6)
(6637, 6)
(6661, 6)
(6685, 6)
(6709, 6)
(6733, 6)
(6757, 6)
(6781, 6)
(6805, 6)
(6829, 6)
(6853, 6)
(6877, 6)
(6901, 6)
(6925, 6)
(6949, 6)
(6973, 6)
(6997, 6)
(7021, 6)
(7045, 6)
(7069, 6)
(7093, 6)
(7117, 6)
(7141, 6)
(7165, 6)
(7191, 6)
(7215, 6)
(7239, 6)
(7262, 6)
(7286, 6)
(7310, 6)
(7334, 6)
(7360, 6)
(7384, 6)
(7408, 6)
(7432, 6)
(7456, 6)
(7480, 6)
(7505, 6)
(7529, 6)
(7555, 6)
(7579, 6)
(7604, 6)
(7631, 6)
(7655, 6)
(7679, 6)
(7703, 6)
(7727, 6)
(7751, 6)
(7775, 6)
(7799, 6)
(7828, 6)
(7853, 6)
(7880, 6)
(7904, 6)
(7940, 6)
(7969, 6)
(7993, 6)
(8017, 6)
(8041, 6)
(8065, 6)
(8089, 6)
(8114, 6)
(8141, 6)
(8166, 6)
(8191, 6)
(8219, 6)
(8247, 6)
(8271, 6)
(8295, 6)
(8322, 6)
(8346, 6)
(8370, 6)
(8394, 6)
(8418, 6)
(8442, 6)
(8466, 6)
(8490, 6)
(8520, 6)
(8544, 6)
(8575, 6)
(8606, 6)
(8630, 6)
(8654, 6)
(8683, 6)
(8707, 6)
(8731, 6)
(8755, 6)
(8783, 6)
(8809, 6)
(8835, 6)
(8859, 6)
(8883, 6)
(8907, 6)
(8931, 6)
(8955, 6)
(8979, 6)
(9003, 6)
(9027, 6)
(9056, 6)
(9082, 6)
(9106, 6)
(9130, 6)
(9154, 6)
(9181, 6)
(9206, 6)
(9230, 6)
(9254, 6)
(9279, 6)
(9306, 6)
(9330, 6)
(9356, 6)
(9380, 6)
(9407, 6)
(9431, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9435, 6)
(9450, 6)
(9475, 6)
(9499, 6)
(9521, 6)
(9553, 6)
(9577, 6)
(9601, 6)
(9625, 6)
(9650, 6)
(9674, 6)
(9699, 6)
(9723, 6)
(9747, 6)
(9771, 6)
(9795, 6)
(9823, 6)
(9847, 6)
(9871, 6)
(9895, 6)
(9920, 6)
(9944, 6)
(9973, 6)
(9998, 6)
(10023, 6)
(10047, 6)
(10071, 6)
(10097, 6)
(10121, 6)
(10145, 6)
(10169, 6)
(10194, 6)
(10218, 6)
(10242, 6)
(10266, 6)
(10291, 6)
(10318, 6)
(10347, 6)
(10373, 6)
(10398, 6)
(10424, 6)
(10454, 6)
(10478, 6)
(10502, 6)
(10526, 6)
(10550, 6)
(10577, 6)
(10601, 6)
(10625, 6)
(10649, 6)
(10673, 6)
(10697, 6)
(10721, 6)
(10745, 6)
(10769, 6)
(10798, 6)
(10823, 6)
(10847, 6)
(10871, 6)
(10895, 6)
(10919, 6)
(10943, 6)
(10967, 6)
(10991, 6)
(11025, 6)
(11049, 6)
(11073, 6)
(11097, 6)
(11121, 6)
(11145, 6)
(11169, 6)
(11193, 6)
(11218, 6)
(11243, 6)
(11270, 6)
(11297, 6)
(11321, 6)
(11346, 6)
(11379, 6)
(11429, 6)
(11461, 6)
(11485, 6)
(11509, 6)
(11533, 6)
(11557, 6)
(11581, 6)
(11605, 6)
(11629, 6)
(11653, 6)
(11677, 6)
(11701, 6)
(11727, 6)
(11751, 6)
(11775, 6)
(11799, 6)
(11823, 6)
(11847, 6)
(11871, 6)
(11895, 6)
(11920, 6)
(11944, 6)
(11968, 6)
(11994, 6)
(12018, 6)
(12042, 6)
(12067, 6)
(12091, 6)
(12122, 6)
(12146, 6)
(12170, 6)
(12194, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12197, 6)
(12212, 6)
(12236, 6)
(12260, 6)
(12284, 6)
(12308, 6)
(12332, 6)
(12356, 6)
(12380, 6)
(12408, 6)
(12432, 6)
(12456, 6)
(12480, 6)
(12504, 6)
(12528, 6)
(12552, 6)
(12576, 6)
(12600, 6)
(12628, 6)
(12652, 6)
(12676, 6)
(12700, 6)
(12724, 6)
(12748, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12750, 6)
(12765, 6)
(12789, 6)
(12813, 6)
(12837, 6)
(12861, 6)
(12891, 6)
(12915, 6)
(12939, 6)
(12968, 6)
(12992, 6)
(13016, 6)
(13043, 6)
(13089, 6)
(13119, 6)
(13144, 6)
(13168, 6)
(13192, 6)
(13216, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13219, 6)
(13234, 6)
(13258, 6)
(13282, 6)
(13307, 6)
(13332, 6)
(13356, 6)
(13380, 6)
(13404, 6)
(13428, 6)
(13453, 6)
(13480, 6)
(13504, 6)
(13528, 6)
(13552, 6)
(13576, 6)
(13599, 6)
(13623, 6)
(13647, 6)
(13675, 6)
(13699, 6)
(13723, 6)
(13748, 6)
(13772, 6)
(13797, 6)
(13822, 6)
(13846, 6)
(13870, 6)
(13894, 6)
(13919, 6)
(13943, 6)
(13967, 6)
(13991, 6)
(14015, 6)
(14039, 6)
(14063, 6)
(14087, 6)
(14111, 6)
(14135, 6)
(14160, 6)
(14184, 6)
(14208, 6)
(14238, 6)
(14265, 6)
(14289, 6)
(14322, 6)
(14346, 6)
(14375, 6)
(14399, 6)
(14423, 6)
(14447, 6)
(14471, 6)
(14495, 6)
(14522, 6)
(14555, 6)
(14583, 6)
(14607, 6)
(14632, 6)
(14658, 6)
(14682, 6)
(14706, 6)
(14736, 6)
(14760, 6)
(14784, 6)
(14808, 6)
(14832, 6)
(14856, 6)
(14880, 6)
(14904, 6)
(14929, 6)
(14953, 6)
(14977, 6)
(15001, 6)
(15025, 6)
(15054, 6)
(15082, 6)
(15107, 6)
(15131, 6)
(15156, 6)
(15180, 6)
(15204, 6)
(15228, 6)
(15252, 6)
(15280, 6)
(15304, 6)
(15328, 6)
(15352, 6)
(15375, 6)
(15399, 6)
(15423, 6)
(15447, 6)
(15471, 6)
(15495, 6)
(15527, 6)
(15551, 6)
(15575, 6)
(15602, 6)
(15626, 6)
(15651, 6)
(15675, 6)
(15699, 6)
(15723, 6)
(15747, 6)
(15771, 6)
(15795, 6)
(15818, 6)
(15842, 6)
(15866, 6)
(15889, 6)
(15913, 6)
(15937, 6)
(15961, 6)
(15984, 6)
(16008, 6)
(16032, 6)
(16056, 6)
(16081, 6)
(16105, 6)
(16129, 6)
(16153, 6)
(16177, 6)
(16201, 6)
(16226, 6)
(16250, 6)
(16274, 6)
(16300, 6)
(16326, 6)
(16350, 6)
(16374, 6)
(16398, 6)
(16423, 6)
(16447, 6)
(16471, 6)
(16495, 6)
(16520, 6)
(16544, 6)
(16568, 6)
(16592, 6)
(16616, 6)
(16640, 6)
(16664, 6)
(16688, 6)
(16713, 6)
(16738, 6)
(16762, 6)
(16791, 6)
(16815, 6)
(16839, 6)
(16863, 6)
(16888, 6)
(16911, 6)
(16935, 6)
(16959, 6)
(16983, 6)
(17007, 6)
(17031, 6)
(17055, 6)
(17082, 6)
(17107, 6)
(17131, 6)
(17155, 6)
(17183, 6)
(17207, 6)
(17233, 6)
(17256, 6)
(17280, 6)
(17306, 6)
(17330, 6)
(17354, 6)
(17378, 6)
(17403, 6)
(17428, 6)
(17453, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17467, 6)
(17481, 6)
(17505, 6)
(17535, 6)
(17564, 6)
(17589, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17591, 6)
(17606, 6)
(17631, 6)
(17656, 6)
(17681, 6)
(17706, 6)
(17730, 6)
(17754, 6)
(17778, 6)
(17802, 6)
(17827, 6)
(17854, 6)
(17880, 6)
(17904, 6)
(17928, 6)
(17954, 6)
(17979, 6)
(18003, 6)
(18027, 6)
(18051, 6)
(18075, 6)
(18099, 6)
(18123, 6)
(18147, 6)
(18171, 6)
(18195, 6)
(18219, 6)
(18243, 6)
(18267, 6)
(18291, 6)
(18315, 6)
(18339, 6)
(18363, 6)
(18387, 6)
(18410, 6)
(18434, 6)
(18458, 6)
(18484, 6)
(18508, 6)
(18531, 6)
(18557, 6)
(18583, 6)
(18607, 6)
(18631, 6)
(18655, 6)
(18679, 6)
(18703, 6)
(18727, 6)
(18755, 6)
(18779, 6)
(18803, 6)
(18827, 6)
(18851, 6)
(18875, 6)
(18899, 6)
(18923, 6)
(18947, 6)
(18971, 6)
(18996, 6)
(19022, 6)
(19036, 6)
(19036, 6)
(19036, 6)
(19036, 6)
(19051, 6)
(19075, 6)
(19099, 6)
(19123, 6)
(19147, 6)
(19171, 6)
(19202, 6)
(19226, 6)
(19250, 6)
(19274, 6)
(19298, 6)
(19322, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19336, 6)
(19351, 6)
(19375, 6)
(19399, 6)
(19423, 6)
(19452, 6)
(19479, 6)
(19505, 6)
(19531, 6)
(19555, 6)
(19580, 6)
(19604, 6)
(19633, 6)
(19660, 6)
(19686, 6)
(19716, 6)
(19756, 6)
(19793, 6)
(19821, 6)
(19856, 6)
(19880, 6)
(19908, 6)
(19957, 6)
(19986, 6)
(20010, 6)
(20036, 6)
(20060, 6)
(20084, 6)
(20086, 6)
(20086, 6)
(20086, 6)
(20086, 6)
(20086, 6)
(20086, 6)
(20086, 6)
(20086, 6)
(20101, 6)
(20128, 6)
(20152, 6)
(20176, 6)
(20200, 6)
(20224, 6)
(20248, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20262, 6)
(20277, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20292, 6)
(20307, 6)
(20331, 6)
(20363, 6)
(20390, 6)
(20414, 6)
(20438, 6)
(20462, 6)
(20486, 6)
(20510, 6)
(20534, 6)
(20558, 6)
(20582, 6)
(20606, 6)
(20630, 6)
(20654, 6)
(20684, 6)
(20711, 6)
(20738, 6)
(20762, 6)
(20786, 6)
(20810, 6)
(20834, 6)
(20857, 6)
(20881, 6)
(20905, 6)
(20929, 6)
(20953, 6)
(20983, 6)
(21007, 6)
(21035, 6)
(21059, 6)
(21083, 6)
(21107, 6)
(21131, 6)
(21155, 6)
(21179, 6)
(21210, 6)
(21234, 6)
(21263, 6)
(21294, 6)
(21318, 6)
(21358, 6)
(21390, 6)
(21422, 6)
(21449, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21452, 6)
(21470, 6)
(21494, 6)
(21518, 6)
(21544, 6)
(21568, 6)
(21594, 6)
(21618, 6)
(21642, 6)
(21665, 6)
(21691, 6)
(21715, 6)
(21739, 6)
(21773, 6)
(21799, 6)
(21823, 6)
(21848, 6)
(21873, 6)
(21897, 6)
(21921, 6)
(21949, 6)
(21973, 6)
(21997, 6)
(22021, 6)
(22050, 6)
(22080, 6)
(22115, 6)
(22140, 6)
(22165, 6)
(22192, 6)
(22216, 6)
(22240, 6)
(22264, 6)
(22290, 6)
(22314, 6)
(22338, 6)
(22362, 6)
(22388, 6)
(22412, 6)
(22436, 6)
(22466, 6)
(22500, 6)
(22530, 6)
(22554, 6)
(22579, 6)
(22603, 6)
(22627, 6)
(22651, 6)
(22675, 6)
(22699, 6)
(22723, 6)
(22747, 6)
(22771, 6)
(22803, 6)
(22829, 6)
(22853, 6)
(22877, 6)
(22901, 6)
(22925, 6)
(22949, 6)
(22973, 6)
(22997, 6)
(23021, 6)
(23045, 6)
(23069, 6)
(23093, 6)
(23118, 6)
(23142, 6)
(23166, 6)
(23196, 6)
(23220, 6)
(23244, 6)
(23268, 6)
(23292, 6)
(23316, 6)
(23341, 6)
(23365, 6)
(23394, 6)
(23425, 6)
(23454, 6)
(23482, 6)
(23524, 6)
(23554, 6)
(23578, 6)
(23602, 6)
(23626, 6)
(23653, 6)
(23679, 6)
(23703, 6)
(23727, 6)
(23754, 6)
(23778, 6)
(23802, 6)
(23829, 6)
(23856, 6)
(23886, 6)
(23910, 6)
(23934, 6)
(23958, 6)
(23982, 6)
(24006, 6)
(24030, 6)
(24057, 6)
(24082, 6)
(24110, 6)
(24135, 6)
(24160, 6)
(24186, 6)
(24210, 6)
(24234, 6)
(24258, 6)
(24283, 6)
(24311, 6)
(24339, 6)
(24363, 6)
(24387, 6)
(24416, 6)
(24441, 6)
(24465, 6)
(24489, 6)
(24515, 6)
(24543, 6)
(24567, 6)
(24592, 6)
(24616, 6)
(24640, 6)
(24665, 6)
(24689, 6)
(24716, 6)
(24742, 6)
(24766, 6)
(24790, 6)
(24816, 6)
(24840, 6)
(24864, 6)
(24888, 6)
(24912, 6)
(24936, 6)
(24960, 6)
(24984, 6)
(25008, 6)
(25032, 6)
(25061, 6)
(25085, 6)
(25110, 6)
(25134, 6)
(25158, 6)
(25182, 6)
(25206, 6)
(25231, 6)
(25255, 6)
(25279, 6)
(25303, 6)
(25327, 6)
(25351, 6)
(25375, 6)
(25400, 6)
(25425, 6)
(25449, 6)
(25473, 6)
(25497, 6)
(25521, 6)
(25545, 6)
(25571, 6)
(25601, 6)
(25627, 6)
(25652, 6)
(25676, 6)
(25700, 6)
(25724, 6)
(25749, 6)
(25778, 6)
(25808, 6)
(25844, 6)
(25873, 6)
(25897, 6)
(25921, 6)
(25945, 6)
(25969, 6)
(26001, 6)
(26027, 6)
(26055, 6)
(26079, 6)
(26103, 6)
(26127, 6)
(26151, 6)
(26175, 6)
(26200, 6)
(26228, 6)
(26257, 6)
(26286, 6)
(26310, 6)
(26335, 6)
(26362, 6)
(26386, 6)
(26410, 6)
(26434, 6)
(26458, 6)
(26482, 6)
(26506, 6)
(26533, 6)
(26557, 6)
(26581, 6)
(26607, 6)
(26631, 6)
(26655, 6)
(26679, 6)
(26704, 6)
(26728, 6)
(26752, 6)
(26788, 6)
(26817, 6)
(26844, 6)
(26869, 6)
(26893, 6)
(26919, 6)
(26947, 6)
(26972, 6)
(26998, 6)
(27025, 6)
(27049, 6)
(27075, 6)
(27099, 6)
(27123, 6)
(27147, 6)
(27175, 6)
(27201, 6)
(27225, 6)
(27249, 6)
(27277, 6)
(27302, 6)
(27327, 6)
(27351, 6)
(27375, 6)
(27399, 6)
(27428, 6)
(27457, 6)
(27484, 6)
(27518, 6)
(27550, 6)
(27575, 6)
(27599, 6)
(27623, 6)
(27647, 6)
(27671, 6)
(27698, 6)
(27725, 6)
(27749, 6)
(27784, 6)
(27830, 6)
(27878, 6)
(27906, 6)
(27936, 6)
(27968, 6)
(27992, 6)
(28017, 6)
(28058, 6)
(28095, 6)
(28125, 6)
(28151, 6)
(28175, 6)
(28199, 6)
(28241, 6)
(28265, 6)
(28289, 6)
(28314, 6)
(28338, 6)
(28363, 6)
(28390, 6)
(28424, 6)
(28448, 6)
(28472, 6)
(28496, 6)
(28520, 6)
(28549, 6)
(28578, 6)
(28609, 6)
(28638, 6)
(28662, 6)
(28686, 6)
(28715, 6)
(28747, 6)
(28771, 6)
(28795, 6)
(28819, 6)
(28849, 6)
(28873, 6)
(28899, 6)
(28929, 6)
(28954, 6)
(28978, 6)
(29002, 6)
(29026, 6)
(29050, 6)
(29074, 6)
(29099, 6)
(29123, 6)
(29149, 6)
(29173, 6)
(29197, 6)
(29221, 6)
(29245, 6)
(29269, 6)
(29294, 6)
(29318, 6)
(29342, 6)
(29366, 6)
(29391, 6)
(29415, 6)
(29439, 6)
(29463, 6)
(29487, 6)
(29512, 6)
(29536, 6)
(29560, 6)
(29584, 6)
(29608, 6)
(29632, 6)
(29656, 6)
(29680, 6)
(29705, 6)
(29729, 6)
(29754, 6)
(29778, 6)
(29802, 6)
(29826, 6)
(29850, 6)
(29873, 6)
(29904, 6)
(29928, 6)
(29952, 6)
(29976, 6)
(30000, 6)
(30023, 6)
(30050, 6)
(30077, 6)
(30101, 6)
(30125, 6)
(30148, 6)
(30169, 6)
(30199, 6)
(30223, 6)
(30247, 6)
(30271, 6)
(30295, 6)
(30319, 6)
(30344, 6)
(30368, 6)
(30392, 6)
(30416, 6)
(30440, 6)
(30464, 6)
(30489, 6)
(30516, 6)
(30548, 6)
(30578, 6)
(30602, 6)
(30630, 6)
(30667, 6)
(30691, 6)
(30715, 6)
(30741, 6)
(30765, 6)
(30789, 6)
(30814, 6)
(30838, 6)
(30857, 6)
(30881, 6)
(30905, 6)
(30929, 6)
(30953, 6)
(30976, 6)
(31000, 6)
(31024, 6)
(31048, 6)
(31072, 6)
(31097, 6)
(31121, 6)
(31145, 6)
(31170, 6)
(31198, 6)
(31222, 6)
(31263, 6)
(31287, 6)
(31311, 6)
(31335, 6)
(31360, 6)
(31384, 6)
(31409, 6)
(31433, 6)
(31457, 6)
(31481, 6)
(31505, 6)
(31531, 6)
(31555, 6)
(31579, 6)
(31603, 6)
(31634, 6)
(31663, 6)
(31687, 6)
(31712, 6)
(31736, 6)
(31760, 6)
(31784, 6)
(31808, 6)
(31832, 6)
(31869, 6)
(31893, 6)
(31917, 6)
(31942, 6)
(31966, 6)
(31991, 6)
(32022, 6)
(32047, 6)
(32071, 6)
(32097, 6)
(32121, 6)
(32147, 6)
(32176, 6)
(32200, 6)
(32224, 6)
(32255, 6)
(32283, 6)
(32308, 6)
(32332, 6)
(32356, 6)
(32386, 6)
(32410, 6)
(32441, 6)
(32465, 6)
(32489, 6)
(32513, 6)

In [192]:
all_df

     Time Temperature Rel. humidity Dew Point        Wind        date
0   00:00        -1°C           75%      -5°C  150°9 Km/h  2017-01-01
1   01:00        -2°C           80%      -5°C  160°9 Km/h  2017-01-01
2   02:00        -3°C           74%      -7°C  160°7 Km/h  2017-01-01
3   03:00        -3°C           80%      -6°C  170°4 Km/h  2017-01-01
4   04:00        -3°C           80%      -6°C  160°7 Km/h  2017-01-01
..    ...         ...           ...       ...         ...         ...
19  19:00         6°C           66%       0°C  150°6 Km/h  2021-01-31
20  20:00         6°C           66%       0°C  150°7 Km/h  2021-01-31
21  21:00         6°C           66%       0°C  130°9 Km/h  2021-01-31
22  22:00         6°C           66%       0°C  160°9 Km/h  2021-01-31
23  23:00         6°C           71%       1°C   90°2 Km/h  2021-01-31

[32513 rows x 6 columns]

In [193]:
set(all_df['Time'])

{'00:00',
 '00:08',
 '00:10',
 '00:11',
 '00:12',
 '00:13',
 '00:16',
 '00:18',
 '00:19',
 '00:23',
 '00:24',
 '00:25',
 '00:28',
 '00:29',
 '00:30',
 '00:31',
 '00:32',
 '00:33',
 '00:34',
 '00:37',
 '00:38',
 '00:39',
 '00:40',
 '00:41',
 '00:43',
 '00:44',
 '00:45',
 '00:46',
 '00:48',
 '00:53',
 '00:57',
 '00:58',
 '01:00',
 '01:04',
 '01:08',
 '01:09',
 '01:13',
 '01:14',
 '01:17',
 '01:20',
 '01:21',
 '01:22',
 '01:25',
 '01:28',
 '01:30',
 '01:31',
 '01:32',
 '01:33',
 '01:35',
 '01:37',
 '01:38',
 '01:40',
 '01:41',
 '01:42',
 '01:43',
 '01:44',
 '01:46',
 '01:47',
 '01:49',
 '01:50',
 '02:00',
 '02:07',
 '02:09',
 '02:10',
 '02:11',
 '02:13',
 '02:14',
 '02:16',
 '02:17',
 '02:18',
 '02:20',
 '02:21',
 '02:22',
 '02:23',
 '02:24',
 '02:25',
 '02:27',
 '02:28',
 '02:29',
 '02:30',
 '02:31',
 '02:32',
 '02:33',
 '02:34',
 '02:35',
 '02:37',
 '02:38',
 '02:39',
 '02:42',
 '02:43',
 '02:45',
 '02:46',
 '02:47',
 '02:49',
 '02:57',
 '03:00',
 '03:05',
 '03:09',
 '03:11',
 '03:12',
 '03:15',
 '03:18',
 '03:19',
 '03:22',
 '03:23',
 '03:24',
 '03:25',
 '03:26',
 '03:27',
 '03:28',
 '03:29',
 '03:30',
 '03:31',
 '03:32',
 '03:33',
 '03:35',
 '03:36',
 '03:37',
 '03:38',
 '03:39',
 '03:40',
 '03:41',
 '03:43',
 '03:45',
 '03:47',
 '03:48',
 '03:49',
 '03:50',
 '03:51',
 '03:56',
 '04:00',
 '04:06',
 '04:07',
 '04:09',
 '04:11',
 '04:13',
 '04:14',
 '04:16',
 '04:19',
 '04:20',
 '04:21',
 '04:22',
 '04:23',
 '04:24',
 '04:25',
 '04:26',
 '04:28',
 '04:29',
 '04:30',
 '04:31',
 '04:35',
 '04:36',
 '04:37',
 '04:38',
 '04:39',
 '04:40',
 '04:42',
 '04:43',
 '04:45',
 '04:46',
 '04:48',
 '04:50',
 '04:51',
 '04:52',
 '04:56',
 '05:00',
 '05:08',
 '05:10',
 '05:11',
 '05:12',
 '05:14',
 '05:15',
 '05:16',
 '05:17',
 '05:18',
 '05:19',
 '05:20',
 '05:21',
 '05:22',
 '05:23',
 '05:24',
 '05:25',
 '05:26',
 '05:27',
 '05:28',
 '05:29',
 '05:30',
 '05:31',
 '05:32',
 '05:33',
 '05:34',
 '05:35',
 '05:36',
 '05:37',
 '05:38',
 '05:39',
 '05:40',
 '05:41',
 '05:42',
 '05:43',
 '05:44',
 '05:45',
 '05:47',
 '05:48',
 '05:50',
 '05:52',
 '05:53',
 '05:54',
 '05:56',
 '05:57',
 '06:00',
 '06:04',
 '06:05',
 '06:07',
 '06:08',
 '06:09',
 '06:10',
 '06:11',
 '06:12',
 '06:13',
 '06:14',
 '06:15',
 '06:16',
 '06:17',
 '06:18',
 '06:20',
 '06:21',
 '06:22',
 '06:23',
 '06:24',
 '06:25',
 '06:26',
 '06:27',
 '06:28',
 '06:29',
 '06:30',
 '06:31',
 '06:32',
 '06:33',
 '06:34',
 '06:35',
 '06:36',
 '06:37',
 '06:39',
 '06:40',
 '06:41',
 '06:42',
 '06:43',
 '06:44',
 '06:45',
 '06:46',
 '06:47',
 '06:48',
 '06:50',
 '06:51',
 '06:52',
 '06:53',
 '06:56',
 '06:57',
 '06:58',
 '07:00',
 '07:08',
 '07:09',
 '07:10',
 '07:11',
 '07:12',
 '07:13',
 '07:14',
 '07:15',
 '07:16',
 '07:18',
 '07:19',
 '07:20',
 '07:21',
 '07:22',
 '07:23',
 '07:24',
 '07:25',
 '07:26',
 '07:28',
 '07:29',
 '07:30',
 '07:31',
 '07:32',
 '07:33',
 '07:34',
 '07:35',
 '07:36',
 '07:37',
 '07:38',
 '07:39',
 '07:40',
 '07:41',
 '07:42',
 '07:43',
 '07:44',
 '07:45',
 '07:46',
 '07:47',
 '07:49',
 '07:51',
 '07:53',
 '07:54',
 '07:56',
 '07:57',
 '08:00',
 '08:06',
 '08:08',
 '08:10',
 '08:11',
 '08:12',
 '08:13',
 '08:14',
 '08:15',
 '08:16',
 '08:17',
 '08:18',
 '08:20',
 '08:21',
 '08:22',
 '08:23',
 '08:25',
 '08:26',
 '08:27',
 '08:29',
 '08:30',
 '08:31',
 '08:32',
 '08:33',
 '08:34',
 '08:35',
 '08:36',
 '08:37',
 '08:38',
 '08:39',
 '08:40',
 '08:41',
 '08:42',
 '08:43',
 '08:44',
 '08:45',
 '08:47',
 '08:48',
 '08:49',
 '08:50',
 '08:51',
 '08:53',
 '08:55',
 '08:56',
 '08:57',
 '09:00',
 '09:04',
 '09:05',
 '09:06',
 '09:07',
 '09:08',
 '09:09',
 '09:10',
 '09:11',
 '09:12',
 '09:13',
 '09:14',
 '09:16',
 '09:17',
 '09:18',
 '09:19',
 '09:20',
 '09:21',
 '09:22',
 '09:23',
 '09:24',
 '09:25',
 '09:27',
 '09:28',
 '09:29',
 '09:30',
 '09:31',
 '09:32',
 '09:33',
 '09:34',
 '09:35',
 '09:36',
 '09:37',
 '09:39',
 '09:40',
 '09:41',
 '09:42',
 '09:43',
 '09:44',
 '09:45',
 '09:46',
 '09:48',
 '09:49',
 '09:50',
 '09:51',
 '09:52',
 '09:57',
 '10:00',
 '10:07',
 '10:10',
 '10:11',
 '10:12',
 '10:13',
 '10:14',
 '10:15',
 '10:17',
 '10:19',
 '10:20',
 '10:21',
 '10:22',
 '10:23',
 '10:24',
 '10:25',
 '10:27',
 '10:28',
 '10:29',
 '10:30',
 '10:31',
 '10:32',
 '10:33',
 '10:34',
 '10:35',
 '10:37',
 '10:38',
 '10:40',
 '10:41',
 '10:42',
 '10:43',
 '10:44',
 '10:45',
 '10:46',
 '10:47',
 '10:48',
 '10:50',
 '10:51',
 '10:52',
 '10:53',
 '10:54',
 '10:57',
 '10:58',
 '11:00',
 '11:06',
 '11:07',
 '11:09',
 '11:10',
 '11:11',
 '11:12',
 '11:13',
 '11:14',
 '11:15',
 '11:17',
 '11:18',
 '11:20',
 '11:21',
 '11:22',
 '11:23',
 '11:24',
 '11:27',
 '11:29',
 '11:30',
 '11:31',
 '11:32',
 '11:33',
 '11:34',
 '11:35',
 '11:36',
 '11:37',
 '11:38',
 '11:39',
 '11:40',
 '11:41',
 '11:42',
 '11:43',
 '11:44',
 '11:46',
 '11:47',
 '11:50',
 '11:51',
 '11:52',
 '11:54',
 '11:55',
 '11:56',
 '11:57',
 '11:59',
 '12:00',
 '12:04',
 '12:05',
 '12:11',
 '12:12',
 '12:15',
 '12:16',
 '12:18',
 '12:21',
 '12:22',
 '12:23',
 '12:24',
 '12:25',
 '12:26',
 '12:27',
 '12:28',
 '12:29',
 '12:30',
 '12:31',
 '12:32',
 '12:33',
 '12:35',
 '12:37',
 '12:38',
 '12:39',
 '12:40',
 '12:41',
 '12:42',
 '12:44',
 '12:45',
 '12:46',
 '12:47',
 '12:48',
 '12:50',
 '12:52',
 '12:53',
 '12:54',
 '12:55',
 '12:56',
 '12:57',
 '13:00',
 '13:06',
 '13:07',
 '13:08',
 '13:11',
 '13:12',
 '13:14',
 '13:16',
 '13:17',
 '13:18',
 '13:19',
 '13:20',
 '13:21',
 '13:22',
 '13:23',
 '13:24',
 '13:25',
 '13:26',
 '13:27',
 '13:28',
 '13:29',
 '13:30',
 '13:31',
 '13:32',
 '13:35',
 '13:36',
 '13:37',
 '13:38',
 '13:40',
 '13:42',
 '13:43',
 '13:44',
 '13:46',
 '13:49',
 '13:50',
 '13:54',
 '13:56',
 '13:57',
 '14:00',
 '14:07',
 '14:12',
 '14:13',
 '14:15',
 '14:16',
 '14:17',
 '14:18',
 '14:19',
 '14:20',
 '14:21',
 '14:22',
 '14:23',
 '14:24',
 '14:26',
 '14:28',
 '14:31',
 '14:32',
 '14:33',
 '14:34',
 '14:37',
 '14:40',
 '14:41',
 '14:42',
 '14:44',
 '14:45',
 '14:47',
 '14:51',
 '14:52',
 '14:53',
 '14:54',
 '14:56',
 '14:57',
 '15:00',
 '15:05',
 '15:06',
 '15:07',
 '15:08',
 '15:09',
 '15:10',
 '15:11',
 '15:13',
 '15:14',
 '15:16',
 '15:17',
 '15:18',
 '15:20',
 '15:21',
 '15:24',
 '15:25',
 '15:26',
 '15:27',
 '15:28',
 '15:29',
 '15:30',
 '15:33',
 '15:34',
 '15:35',
 '15:37',
 '15:38',
 '15:39',
 '15:40',
 '15:42',
 '15:43',
 '15:44',
 '15:45',
 '15:46',
 '15:48',
 '15:49',
 '15:51',
 '15:52',
 '15:53',
 '15:56',
 '15:57',
 '16:00',
 '16:03',
 '16:04',
 '16:06',
 '16:08',
 '16:09',
 '16:10',
 '16:11',
 '16:12',
 '16:13',
 '16:14',
 '16:16',
 '16:18',
 '16:20',
 '16:21',
 '16:22',
 '16:23',
 '16:24',
 '16:26',
 '16:27',
 '16:29',
 '16:30',
 '16:31',
 '16:33',
 '16:34',
 '16:35',
 '16:36',
 '16:37',
 '16:38',
 '16:39',
 '16:40',
 '16:41',
 '16:42',
 '16:44',
 '16:46',
 '16:49',
 '16:51',
 '16:56',
 '16:59',
 '17:00',
 '17:12',
 '17:13',
 '17:14',
 '17:15',
 '17:16',
 '17:17',
 '17:19',
 '17:20',
 '17:21',
 '17:22',
 '17:23',
 '17:24',
 '17:27',
 '17:28',
 '17:31',
 '17:32',
 '17:33',
 '17:34',
 '17:37',
 '17:39',
 '17:40',
 '17:41',
 '17:42',
 '17:43',
 '17:45',
 '17:46',
 '17:49',
 '17:50',
 '17:51',
 '17:56',
 '17:57',
 '18:00',
 '18:05',
 '18:06',
 '18:08',
 '18:10',
 '18:11',
 '18:12',
 '18:13',
 '18:14',
 '18:15',
 '18:16',
 '18:17',
 '18:20',
 '18:22',
 '18:23',
 '18:24',
 '18:27',
 '18:28',
 '18:29',
 '18:30',
 '18:33',
 '18:36',
 '18:38',
 '18:39',
 '18:40',
 '18:41',
 '18:42',
 '18:43',
 '18:44',
 '18:45',
 '18:46',
 '18:47',
 '18:49',
 '18:50',
 '18:55',
 '18:57',
 '19:00',
 '19:05',
 '19:08',
 '19:09',
 '19:10',
 '19:11',
 '19:13',
 '19:14',
 '19:15',
 '19:17',
 '19:18',
 '19:19',
 '19:20',
 '19:21',
 '19:22',
 '19:23',
 '19:25',
 '19:26',
 '19:27',
 '19:30',
 '19:31',
 '19:32',
 '19:33',
 '19:34',
 '19:35',
 '19:36',
 '19:38',
 '19:40',
 '19:41',
 '19:42',
 '19:44',
 '19:46',
 '19:47',
 '19:48',
 '19:53',
 '19:54',
 '19:56',
 '19:57',
 '20:00',
 '20:07',
 '20:08',
 '20:10',
 '20:11',
 '20:12',
 '20:14',
 '20:15',
 '20:16',
 '20:17',
 '20:20',
 '20:21',
 '20:23',
 '20:24',
 '20:25',
 '20:27',
 '20:29',
 '20:32',
 '20:33',
 '20:35',
 '20:36',
 '20:42',
 '20:43',
 '20:45',
 '20:48',
 '20:49',
 '20:50',
 '20:51',
 '20:57',
 '21:00',
 '21:07',
 '21:09',
 '21:10',
 '21:12',
 '21:13',
 '21:14',
 '21:19',
 '21:21',
 '21:25',
 '21:26',
 '21:28',
 '21:29',
 '21:30',
 '21:32',
 '21:34',
 '21:37',
 '21:39',
 '21:40',
 '21:41',
 '21:42',
 '21:43',
 '21:44',
 '21:46',
 '21:47',
 '21:50',
 '21:54',
 '21:57',
 '22:00',
 '22:05',
 '22:06',
 '22:07',
 '22:09',
 '22:12',
 '22:14',
 '22:15',
 '22:16',
 '22:17',
 '22:18',
 '22:19',
 '22:20',
 '22:21',
 '22:22',
 '22:25',
 '22:26',
 '22:28',
 '22:29',
 '22:30',
 '22:31',
 '22:34',
 '22:36',
 '22:37',
 '22:39',
 '22:40',
 '22:41',
 '22:42',
 '22:44',
 '22:45',
 '22:47',
 '22:50',
 '22:51',
 '22:52',
 '22:57',
 '23:00',
 '23:04',
 '23:08',
 '23:09',
 '23:10',
 '23:13',
 '23:14',
 '23:16',
 '23:17',
 '23:18',
 '23:19',
 '23:20',
 '23:21',
 '23:22',
 '23:24',
 '23:25',
 '23:27',
 '23:29',
 '23:30',
 '23:33',
 '23:34',
 '23:35',
 '23:37',
 '23:38',
 '23:39',
 '23:40',
 '23:41',
 '23:42',
 '23:43',
 '23:44',
 '23:45',
 '23:46',
 '23:47',
 '23:52',
 '23:55',
 '23:57',
 '23:58'}

In [194]:
# all_df.rename(columns={'index': 'hour'}, inplace=True)

In [195]:
# all_df['hour'] = all_df['hour'].apply(lambda x: ('0'+str(x))[-2:])

In [196]:
# all_df['hour']

In [197]:
all_df['datetime'] = all_df['date'] + ' ' + all_df['Time'] + ':00'

In [198]:
all_df

,Time,Temperature,Rel. humidity,Dew Point,Wind,date,datetime
0,00:00,-1°C,75%,-5°C,150°9 Km/h,2017-01-01,2017-01-01 00:00:00
1,01:00,-2°C,80%,-5°C,160°9 Km/h,2017-01-01,2017-01-01 01:00:00
2,02:00,-3°C,74%,-7°C,160°7 Km/h,2017-01-01,2017-01-01 02:00:00
3,03:00,-3°C,80%,-6°C,170°4 Km/h,2017-01-01,2017-01-01 03:00:00
4,04:00,-3°C,80%,-6°C,160°7 Km/h,2017-01-01,2017-01-01 04:00:00
...,...,...,...,...,...,...,...
19,19:00,6°C,66%,0°C,150°6 Km/h,2021-01-31,2021-01-31 19:00:00
20,20:00,6°C,66%,0°C,150°7 Km/h,2021-01-31,2021-01-31 20:00:00
21,21:00,6°C,66%,0°C,130°9 Km/h,2021-01-31,2021-01-31 21:00:00
22,22:00,6°C,66%,0°C,160°9 Km/h,2021-01-31,2021-01-31 22:00:00
23,23:00,6°C,71%,1°C,90°2 Km/h,2021-01-31,2021-01-31 23:00:00

In [199]:
set(all_df['Temperature'])

{'-10°C',
 '-11°C',
 '-12°C',
 '-13°C',
 '-14°C',
 '-15°C',
 '-16°C',
 '-17°C',
 '-18°C',
 '-1°C',
 '-2°C',
 '-3°C',
 '-4°C',
 '-5°C',
 '-6°C',
 '-7°C',
 '-8°C',
 '-9°C',
 '0°C',
 '10°C',
 '11°C',
 '12°C',
 '13°C',
 '14°C',
 '15°C',
 '16°C',
 '17°C',
 '18°C',
 '19°C',
 '1°C',
 '20°C',
 '21°C',
 '22°C',
 '23°C',
 '24°C',
 '25°C',
 '26°C',
 '27°C',
 '28°C',
 '29°C',
 '2°C',
 '30°C',
 '31°C',
 '32°C',
 '33°C',
 '34°C',
 '35°C',
 '36°C',
 '37°C',
 '3°C',
 '4°C',
 '5°C',
 '6°C',
 '7°C',
 '8°C',
 '9°C'}

In [200]:
all_df['Temperature'] = all_df['Temperature'].apply(lambda x: int(x.split('°')[0]))
all_df['Temperature']

0    -1
1    -2
2    -3
3    -3
4    -3
     ..
19    6
20    6
21    6
22    6
23    6
Name: Temperature, Length: 32513, dtype: int64

In [201]:
set(all_df['Rel. humidity'])

{'10%',
 '100%',
 '11%',
 '12%',
 '13%',
 '14%',
 '15%',
 '16%',
 '17%',
 '18%',
 '19%',
 '20%',
 '21%',
 '22%',
 '23%',
 '24%',
 '25%',
 '26%',
 '27%',
 '28%',
 '29%',
 '30%',
 '31%',
 '32%',
 '33%',
 '34%',
 '35%',
 '36%',
 '37%',
 '38%',
 '39%',
 '40%',
 '41%',
 '42%',
 '43%',
 '44%',
 '45%',
 '46%',
 '47%',
 '48%',
 '49%',
 '50%',
 '51%',
 '52%',
 '53%',
 '54%',
 '55%',
 '56%',
 '57%',
 '58%',
 '59%',
 '60%',
 '61%',
 '62%',
 '63%',
 '64%',
 '65%',
 '66%',
 '67%',
 '68%',
 '69%',
 '70%',
 '71%',
 '72%',
 '73%',
 '74%',
 '75%',
 '76%',
 '77%',
 '78%',
 '79%',
 '80%',
 '81%',
 '82%',
 '83%',
 '84%',
 '85%',
 '86%',
 '87%',
 '88%',
 '89%',
 '93%',
 '94%'}

In [202]:
all_df['Rel. humidity'] = all_df['Rel. humidity'].apply(lambda x: int(x.split('%')[0]))
all_df['Rel. humidity']

0     75
1     80
2     74
3     80
4     80
      ..
19    66
20    66
21    66
22    66
23    71
Name: Rel. humidity, Length: 32513, dtype: int64

In [203]:
set(all_df['Dew Point'])

{'-10°C',
 '-11°C',
 '-12°C',
 '-13°C',
 '-14°C',
 '-15°C',
 '-16°C',
 '-17°C',
 '-18°C',
 '-19°C',
 '-1°C',
 '-20°C',
 '-21°C',
 '-22°C',
 '-23°C',
 '-24°C',
 '-25°C',
 '-26°C',
 '-27°C',
 '-28°C',
 '-2°C',
 '-30°C',
 '-3°C',
 '-4°C',
 '-5°C',
 '-6°C',
 '-7°C',
 '-8°C',
 '-9°C',
 '0°C',
 '10°C',
 '11°C',
 '12°C',
 '13°C',
 '14°C',
 '15°C',
 '16°C',
 '17°C',
 '18°C',
 '19°C',
 '1°C',
 '20°C',
 '21°C',
 '22°C',
 '23°C',
 '24°C',
 '25°C',
 '26°C',
 '27°C',
 '2°C',
 '3°C',
 '4°C',
 '5°C',
 '6°C',
 '7°C',
 '8°C',
 '9°C'}

In [204]:
all_df['Dew Point'] = all_df['Dew Point'].apply(lambda x: int(x.split('°')[0]))
all_df['Dew Point']

0    -5
1    -5
2    -7
3    -6
4    -6
     ..
19    0
20    0
21    0
22    0
23    1
Name: Dew Point, Length: 32513, dtype: int64

In [205]:
set(all_df['Wind'])

{'100°11 Km/h',
 '100°13 Km/h',
 '100°15 Km/h',
 '100°17 Km/h',
 '100°19 Km/h',
 '100°2 Km/h',
 '100°20 Km/h',
 '100°22 Km/h',
 '100°24 Km/h',
 '100°26 Km/h',
 '100°28 Km/h',
 '100°31 Km/h',
 '100°35 Km/h',
 '100°4 Km/h',
 '100°6 Km/h',
 '100°7 Km/h',
 '100°9 Km/h',
 '10°11 Km/h',
 '10°13 Km/h',
 '10°15 Km/h',
 '10°17 Km/h',
 '10°19 Km/h',
 '10°2 Km/h',
 '10°20 Km/h',
 '10°22 Km/h',
 '10°24 Km/h',
 '10°26 Km/h',
 '10°28 Km/h',
 '10°30 Km/h',
 '10°31 Km/h',
 '10°4 Km/h',
 '10°6 Km/h',
 '10°7 Km/h',
 '10°9 Km/h',
 '110°11 Km/h',
 '110°13 Km/h',
 '110°15 Km/h',
 '110°17 Km/h',
 '110°19 Km/h',
 '110°2 Km/h',
 '110°20 Km/h',
 '110°22 Km/h',
 '110°24 Km/h',
 '110°26 Km/h',
 '110°28 Km/h',
 '110°30 Km/h',
 '110°31 Km/h',
 '110°35 Km/h',
 '110°39 Km/h',
 '110°4 Km/h',
 '110°6 Km/h',
 '110°7 Km/h',
 '110°9 Km/h',
 '120°11 Km/h',
 '120°13 Km/h',
 '120°15 Km/h',
 '120°17 Km/h',
 '120°19 Km/h',
 '120°2 Km/h',
 '120°20 Km/h',
 '120°22 Km/h',
 '120°24 Km/h',
 '120°26 Km/h',
 '120°30 Km/h',
 '120°31 Km/h',
 '120°37 Km/h',
 '120°4 Km/h',
 '120°41 Km/h',
 '120°52 Km/h',
 '120°6 Km/h',
 '120°7 Km/h',
 '120°9 Km/h',
 '130°11 Km/h',
 '130°13 Km/h',
 '130°15 Km/h',
 '130°17 Km/h',
 '130°19 Km/h',
 '130°2 Km/h',
 '130°20 Km/h',
 '130°22 Km/h',
 '130°24 Km/h',
 '130°26 Km/h',
 '130°28 Km/h',
 '130°33 Km/h',
 '130°37 Km/h',
 '130°39 Km/h',
 '130°4 Km/h',
 '130°46 Km/h',
 '130°6 Km/h',
 '130°7 Km/h',
 '130°9 Km/h',
 '140°11 Km/h',
 '140°13 Km/h',
 '140°15 Km/h',
 '140°17 Km/h',
 '140°19 Km/h',
 '140°2 Km/h',
 '140°20 Km/h',
 '140°22 Km/h',
 '140°24 Km/h',
 '140°26 Km/h',
 '140°28 Km/h',
 '140°33 Km/h',
 '140°37 Km/h',
 '140°4 Km/h',
 '140°6 Km/h',
 '140°7 Km/h',
 '140°9 Km/h',
 '150°11 Km/h',
 '150°13 Km/h',
 '150°15 Km/h',
 '150°17 Km/h',
 '150°19 Km/h',
 '150°2 Km/h',
 '150°20 Km/h',
 '150°22 Km/h',
 '150°24 Km/h',
 '150°26 Km/h',
 '150°28 Km/h',
 '150°30 Km/h',
 '150°31 Km/h',
 '150°4 Km/h',
 '150°6 Km/h',
 '150°7 Km/h',
 '150°9 Km/h',
 '160°11 Km/h',
 '160°13 Km/h',
 '160°15 Km/h',
 '160°17 Km/h',
 '160°19 Km/h',
 '160°2 Km/h',
 '160°20 Km/h',
 '160°22 Km/h',
 '160°24 Km/h',
 '160°26 Km/h',
 '160°28 Km/h',
 '160°31 Km/h',
 '160°4 Km/h',
 '160°6 Km/h',
 '160°7 Km/h',
 '160°9 Km/h',
 '170°11 Km/h',
 '170°13 Km/h',
 '170°15 Km/h',
 '170°17 Km/h',
 '170°19 Km/h',
 '170°2 Km/h',
 '170°20 Km/h',
 '170°22 Km/h',
 '170°24 Km/h',
 '170°28 Km/h',
 '170°30 Km/h',
 '170°31 Km/h',
 '170°33 Km/h',
 '170°37 Km/h',
 '170°4 Km/h',
 '170°6 Km/h',
 '170°7 Km/h',
 '170°9 Km/h',
 '180°11 Km/h',
 '180°13 Km/h',
 '180°15 Km/h',
 '180°17 Km/h',
 '180°19 Km/h',
 '180°2 Km/h',
 '180°20 Km/h',
 '180°22 Km/h',
 '180°24 Km/h',
 '180°26 Km/h',
 '180°28 Km/h',
 '180°30 Km/h',
 '180°4 Km/h',
 '180°6 Km/h',
 '180°7 Km/h',
 '180°9 Km/h',
 '190°11 Km/h',
 '190°13 Km/h',
 '190°15 Km/h',
 '190°17 Km/h',
 '190°19 Km/h',
 '190°2 Km/h',
 '190°20 Km/h',
 '190°22 Km/h',
 '190°24 Km/h',
 '190°26 Km/h',
 '190°28 Km/h',
 '190°30 Km/h',
 '190°37 Km/h',
 '190°4 Km/h',
 '190°6 Km/h',
 '190°7 Km/h',
 '190°9 Km/h',
 '200°11 Km/h',
 '200°13 Km/h',
 '200°15 Km/h',
 '200°17 Km/h',
 '200°19 Km/h',
 '200°2 Km/h',
 '200°20 Km/h',
 '200°22 Km/h',
 '200°24 Km/h',
 '200°26 Km/h',
 '200°28 Km/h',
 '200°30 Km/h',
 '200°33 Km/h',
 '200°35 Km/h',
 '200°37 Km/h',
 '200°39 Km/h',
 '200°4 Km/h',
 '200°46 Km/h',
 '200°48 Km/h',
 '200°6 Km/h',
 '200°7 Km/h',
 '200°9 Km/h',
 '20°11 Km/h',
 '20°13 Km/h',
 '20°15 Km/h',
 '20°17 Km/h',
 '20°19 Km/h',
 '20°2 Km/h',
 '20°20 Km/h',
 '20°22 Km/h',
 '20°24 Km/h',
 '20°26 Km/h',
 '20°4 Km/h',
 '20°6 Km/h',
 '20°7 Km/h',
 '20°9 Km/h',
 '210°11 Km/h',
 '210°13 Km/h',
 '210°15 Km/h',
 '210°17 Km/h',
 '210°19 Km/h',
 '210°2 Km/h',
 '210°20 Km/h',
 '210°22 Km/h',
 '210°24 Km/h',
 '210°26 Km/h',
 '210°28 Km/h',
 '210°30 Km/h',
 '210°31 Km/h',
 '210°33 Km/h',
 '210°35 Km/h',
 '210°37 Km/h',
 '210°39 Km/h',
 '210°4 Km/h',
 '210°41 Km/h',
 '210°43 Km/h',
 '210°48 Km/h',
 '210°6 Km/h',
 '210°7 Km/h',
 '210°9 Km/h',
 '220°11 Km/h',
 '220°13 Km/h',
 '220°15 Km/h',
 '220°17 Km/h',
 '220°19 Km/h',
 '220°2 Km/h',
 '220°20 Km/h',
 '220°22 Km/h',
 '220°24 Km/h',
 '220°26 Km/h',
 '220°28 Km/h',
 '220°30 Km/h',
 '220°31 Km/h',
 '220°35 Km/h',
 '220°37 Km/h',
 '220°39 Km/h',
 '220°4 Km/h',
 '220°41 Km/h',
 '220°44 Km/h',
 '220°6 Km/h',
 '220°7 Km/h',
 '220°9 Km/h',
 '230°11 Km/h',
 '230°13 Km/h',
 '230°15 Km/h',
 '230°17 Km/h',
 '230°19 Km/h',
 '230°2 Km/h',
 '230°20 Km/h',
 '230°22 Km/h',
 '230°24 Km/h',
 '230°26 Km/h',
 '230°28 Km/h',
 '230°30 Km/h',
 '230°31 Km/h',
 '230°33 Km/h',
 '230°35 Km/h',
 '230°37 Km/h',
 '230°39 Km/h',
 '230°4 Km/h',
 '230°41 Km/h',
 '230°46 Km/h',
 '230°6 Km/h',
 '230°7 Km/h',
 '230°9 Km/h',
 '240°11 Km/h',
 '240°13 Km/h',
 '240°15 Km/h',
 '240°17 Km/h',
 '240°19 Km/h',
 '240°2 Km/h',
 '240°20 Km/h',
 '240°22 Km/h',
 '240°24 Km/h',
 '240°26 Km/h',
 '240°28 Km/h',
 '240°30 Km/h',
 '240°31 Km/h',
 '240°33 Km/h',
 '240°35 Km/h',
 '240°37 Km/h',
 '240°4 Km/h',
 '240°6 Km/h',
 '240°7 Km/h',
 '240°9 Km/h',
 '250°11 Km/h',
 '250°13 Km/h',
 '250°15 Km/h',
 '250°17 Km/h',
 '250°19 Km/h',
 '250°2 Km/h',
 '250°20 Km/h',
 '250°22 Km/h',
 '250°24 Km/h',
 '250°26 Km/h',
 '250°28 Km/h',
 '250°30 Km/h',
 '250°31 Km/h',
 '250°33 Km/h',
 '250°35 Km/h',
 '250°4 Km/h',
 '250°6 Km/h',
 '250°7 Km/h',
 '250°9 Km/h',
 '260°11 Km/h',
 '260°13 Km/h',
 '260°15 Km/h',
 '260°17 Km/h',
 '260°19 Km/h',
 '260°2 Km/h',
 '260°20 Km/h',
 '260°22 Km/h',
 '260°24 Km/h',
 '260°26 Km/h',
 '260°28 Km/h',
 '260°30 Km/h',
 '260°31 Km/h',
 '260°33 Km/h',
 '260°35 Km/h',
 '260°39 Km/h',
 '260°4 Km/h',
 '260°41 Km/h',
 '260°43 Km/h',
 '260°6 Km/h',
 '260°7 Km/h',
 '260°9 Km/h',
 '270°11 Km/h',
 '270°13 Km/h',
 '270°15 Km/h',
 '270°17 Km/h',
 '270°19 Km/h',
 '270°2 Km/h',
 '270°20 Km/h',
 '270°22 Km/h',
 '270°24 Km/h',
 '270°26 Km/h',
 '270°28 Km/h',
 '270°30 Km/h',
 '270°31 Km/h',
 '270°33 Km/h',
 '270°35 Km/h',
 '270°37 Km/h',
 '270°39 Km/h',
 '270°4 Km/h',
 '270°41 Km/h',
 '270°43 Km/h',
 '270°44 Km/h',
 '270°46 Km/h',
 '270°48 Km/h',
 '270°6 Km/h',
 '270°7 Km/h',
 '270°9 Km/h',
 '280°11 Km/h',
 '280°13 Km/h',
 '280°15 Km/h',
 '280°17 Km/h',
 '280°19 Km/h',
 '280°2 Km/h',
 '280°20 Km/h',
 '280°22 Km/h',
 '280°24 Km/h',
 '280°26 Km/h',
 '280°28 Km/h',
 '280°30 Km/h',
 '280°31 Km/h',
 '280°33 Km/h',
 '280°35 Km/h',
 '280°37 Km/h',
 '280°39 Km/h',
 '280°4 Km/h',
 '280°44 Km/h',
 '280°6 Km/h',
 '280°7 Km/h',
 '280°9 Km/h',
 '290°11 Km/h',
 '290°13 Km/h',
 '290°15 Km/h',
 '290°17 Km/h',
 '290°19 Km/h',
 '290°2 Km/h',
 '290°20 Km/h',
 '290°22 Km/h',
 '290°24 Km/h',
 '290°26 Km/h',
 '290°28 Km/h',
 '290°30 Km/h',
 '290°31 Km/h',
 '290°33 Km/h',
 '290°35 Km/h',
 '290°37 Km/h',
 '290°4 Km/h',
 '290°41 Km/h',
 '290°43 Km/h',
 '290°46 Km/h',
 '290°6 Km/h',
 '290°7 Km/h',
 '290°9 Km/h',
 '300°11 Km/h',
 '300°13 Km/h',
 '300°15 Km/h',
 '300°17 Km/h',
 '300°19 Km/h',
 '300°2 Km/h',
 '300°20 Km/h',
 '300°22 Km/h',
 '300°24 Km/h',
 '300°26 Km/h',
 '300°28 Km/h',
 '300°30 Km/h',
 '300°31 Km/h',
 '300°33 Km/h',
 '300°35 Km/h',
 '300°4 Km/h',
 '300°44 Km/h',
 '300°6 Km/h',
 '300°7 Km/h',
 '300°9 Km/h',
 '30°11 Km/h',
 '30°13 Km/h',
 '30°15 Km/h',
 '30°17 Km/h',
 '30°19 Km/h',
 '30°2 Km/h',
 '30°20 Km/h',
 '30°22 Km/h',
 '30°24 Km/h',
 '30°26 Km/h',
 '30°28 Km/h',
 '30°30 Km/h',
 '30°4 Km/h',
 '30°6 Km/h',
 '30°7 Km/h',
 '30°9 Km/h',
 '310°11 Km/h',
 '310°13 Km/h',
 '310°15 Km/h',
 '310°17 Km/h',
 '310°19 Km/h',
 '310°2 Km/h',
 '310°20 Km/h',
 '310°22 Km/h',
 '310°24 Km/h',
 '310°26 Km/h',
 '310°28 Km/h',
 '310°30 Km/h',
 '310°31 Km/h',
 '310°33 Km/h',
 '310°37 Km/h',
 '310°4 Km/h',
 '310°41 Km/h',
 '310°6 Km/h',
 '310°7 Km/h',
 '310°9 Km/h',
 '320°11 Km/h',
 '320°13 Km/h',
 '320°15 Km/h',
 '320°17 Km/h',
 '320°19 Km/h',
 '320°2 Km/h',
 '320°20 Km/h',
 '320°22 Km/h',
 '320°24 Km/h',
 '320°26 Km/h',
 '320°28 Km/h',
 '320°30 Km/h',
 '320°31 Km/h',
 '320°33 Km/h',
 '320°35 Km/h',
 '320°37 Km/h',
 '320°4 Km/h',
 '320°46 Km/h',
 '320°6 Km/h',
 '320°7 Km/h',
 '320°9 Km/h',
 '330°11 Km/h',
 '330°13 Km/h',
 '330°15 Km/h',
 '330°17 Km/h',
 '330°19 Km/h',
 '330°2 Km/h',
 '330°20 Km/h',
 '330°22 Km/h',
 '330°24 Km/h',
 '330°26 Km/h',
 '330°28 Km/h',
 '330°30 Km/h',
 '330°31 Km/h',
 '330°33 Km/h',
 '330°35 Km/h',
 '330°37 Km/h',
 '330°4 Km/h',
 '330°41 Km/h',
 '330°43 Km/h',
 '330°6 Km/h',
 '330°7 Km/h',
 '330°9 Km/h',
 '340°11 Km/h',
 '340°13 Km/h',
 '340°15 Km/h',
 '340°17 Km/h',
 '340°19 Km/h',
 '340°2 Km/h',
 '340°20 Km/h',
 '340°22 Km/h',
 '340°24 Km/h',
 '340°26 Km/h',
 '340°28 Km/h',
 '340°30 Km/h',
 '340°31 Km/h',
 '340°33 Km/h',
 '340°37 Km/h',
 '340°39 Km/h',
 '340°4 Km/h',
 '340°6 Km/h',
 '340°7 Km/h',
 '340°9 Km/h',
 '350°11 Km/h',
 '350°13 Km/h',
 '350°15 Km/h',
 '350°17 Km/h',
 '350°19 Km/h',
 '350°2 Km/h',
 '350°20 Km/h',
 '350°22 Km/h',
 '350°24 Km/h',
 '350°26 Km/h',
 '350°28 Km/h',
 '350°30 Km/h',
 '350°31 Km/h',
 '350°4 Km/h',
 '350°6 Km/h',
 '350°7 Km/h',
 '350°9 Km/h',
 '360°11 Km/h',
 '360°13 Km/h',
 '360°15 Km/h',
 '360°17 Km/h',
 '360°19 Km/h',
 '360°2 Km/h',
 '360°20 Km/h',
 '360°22 Km/h',
 '360°24 Km/h',
 '360°26 Km/h',
 '360°28 Km/h',
 '360°30 Km/h',
 '360°31 Km/h',
 '360°33 Km/h',
 '360°4 Km/h',
 '360°6 Km/h',
 '360°7 Km/h',
 '360°9 Km/h',
 '40°11 Km/h',
 '40°13 Km/h',
 '40°15 Km/h',
 '40°17 Km/h',
 '40°19 Km/h',
 '40°2 Km/h',
 '40°20 Km/h',
 '40°22 Km/h',
 '40°26 Km/h',
 '40°28 Km/h',
 '40°30 Km/h',
 '40°35 Km/h',
 '40°4 Km/h',
 '40°6 Km/h',
 '40°7 Km/h',
 '40°9 Km/h',
 '50°11 Km/h',
 '50°13 Km/h',
 '50°15 Km/h',
 '50°17 Km/h',
 '50°19 Km/h',
 '50°2 Km/h',
 '50°20 Km/h',
 '50°22 Km/h',
 '50°24 Km/h',
 '50°26 Km/h',
 '50°28 Km/h',
 '50°37 Km/h',
 '50°4 Km/h',
 '50°6 Km/h',
 '50°7 Km/h',
 '50°9 Km/h',
 '60°11 Km/h',
 '60°13 Km/h',
 '60°15 Km/h',
 '60°17 Km/h',
 '60°19 Km/h',
 '60°2 Km/h',
 '60°20 Km/h',
 '60°22 Km/h',
 '60°24 Km/h',
 '60°26 Km/h',
 '60°28 Km/h',
 '60°33 Km/h',
 '60°4 Km/h',
 '60°6 Km/h',
 '60°7 Km/h',
 '60°9 Km/h',
 '70°11 Km/h',
 '70°13 Km/h',
 '70°15 Km/h',
 '70°17 Km/h',
 '70°19 Km/h',
 '70°2 Km/h',
 '70°20 Km/h',
 '70°22 Km/h',
 '70°24 Km/h',
 '70°26 Km/h',
 '70°28 Km/h',
 '70°30 Km/h',
 '70°31 Km/h',
 '70°37 Km/h',
 '70°4 Km/h',
 '70°6 Km/h',
 '70°7 Km/h',
 '70°9 Km/h',
 '80°11 Km/h',
 '80°13 Km/h',
 '80°15 Km/h',
 '80°17 Km/h',
 '80°19 Km/h',
 '80°2 Km/h',
 '80°20 Km/h',
 '80°22 Km/h',
 '80°24 Km/h',
 '80°26 Km/h',
 '80°28 Km/h',
 '80°30 Km/h',
 '80°31 Km/h',
 '80°33 Km/h',
 '80°35 Km/h',
 '80°4 Km/h',
 '80°6 Km/h',
 '80°7 Km/h',
 '80°9 Km/h',
 '90°11 Km/h',
 '90°13 Km/h',
 '90°15 Km/h',
 '90°17 Km/h',
 '90°19 Km/h',
 '90°2 Km/h',
 '90°20 Km/h',
 '90°22 Km/h',
 '90°24 Km/h',
 '90°26 Km/h',
 '90°28 Km/h',
 '90°30 Km/h',
 '90°4 Km/h',
 '90°6 Km/h',
 '90°7 Km/h',
 '90°9 Km/h',
 'Calm'}

In [206]:
all_df['Wind'] = all_df['Wind'].apply(lambda x: int(x.split('°')[1].split(' ')[0] if len(x) > 4 else 0))
all_df['Wind']

0     9
1     9
2     7
3     4
4     7
     ..
19    6
20    7
21    9
22    9
23    2
Name: Wind, Length: 32513, dtype: int64

In [207]:
all_df

,Time,Temperature,Rel. humidity,Dew Point,Wind,date,datetime
0,00:00,-1,75,-5,9,2017-01-01,2017-01-01 00:00:00
1,01:00,-2,80,-5,9,2017-01-01,2017-01-01 01:00:00
2,02:00,-3,74,-7,7,2017-01-01,2017-01-01 02:00:00
3,03:00,-3,80,-6,4,2017-01-01,2017-01-01 03:00:00
4,04:00,-3,80,-6,7,2017-01-01,2017-01-01 04:00:00
...,...,...,...,...,...,...,...
19,19:00,6,66,0,6,2021-01-31,2021-01-31 19:00:00
20,20:00,6,66,0,7,2021-01-31,2021-01-31 20:00:00
21,21:00,6,66,0,9,2021-01-31,2021-01-31 21:00:00
22,22:00,6,66,0,9,2021-01-31,2021-01-31 22:00:00
23,23:00,6,71,1,2,2021-01-31,2021-01-31 23:00:00

In [208]:
all_df.columns

Index(['Time', 'Temperature', 'Rel. humidity', 'Dew Point', 'Wind', 'date',
       'datetime'],
      dtype='object')

In [209]:
interested = ['Temperature', 'Rel. humidity', 'Dew Point', 'Wind', 'datetime']
df2 = all_df[interested]
df2

    Temperature  Rel. humidity  Dew Point  Wind             datetime
0            -1             75         -5     9  2017-01-01 00:00:00
1            -2             80         -5     9  2017-01-01 01:00:00
2            -3             74         -7     7  2017-01-01 02:00:00
3            -3             80         -6     4  2017-01-01 03:00:00
4            -3             80         -6     7  2017-01-01 04:00:00
..          ...            ...        ...   ...                  ...
19            6             66          0     6  2021-01-31 19:00:00
20            6             66          0     7  2021-01-31 20:00:00
21            6             66          0     9  2021-01-31 21:00:00
22            6             66          0     9  2021-01-31 22:00:00
23            6             71          1     2  2021-01-31 23:00:00

[32513 rows x 5 columns]

In [213]:
# pd.merge(df, df2, on='datetime', how='left').info()
pd.merge(df, df2, how='inner').info()

# 1번은 datetime에 넣어주는데 null 값이 생기므로 null 값을 처리해야함
# 2번은 애초에 두개의 데이터의 datetime이 같이 있는 것만 가져오니 null값을 빼고 가져옴

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30432 entries, 0 to 30431
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       30432 non-null  object
 1   regular        30432 non-null  float64
 2   casual         30432 non-null  float64
 3   group          30432 non-null  float64
 4   Temperature    30432 non-null  int64
 5   Rel. humidity  30432 non-null  int64
 6   Dew Point      30432 non-null  int64
 7   Wind           30432 non-null  int64
dtypes: float64(3), int64(4), object(1)
memory usage: 1.9+ MB

In [46]:
df

,datetime,regular,casual,group,Temperature,Rel. humidity,Dew Point,Wind
0,2017-01-01 00:00:00,63.0,13.0,1.0,-1,75,-5,9
1,2017-01-01 01:00:00,55.0,21.0,0.0,-2,80,-5,9
2,2017-01-01 02:00:00,38.0,19.0,0.0,-3,74,-7,7
3,2017-01-01 03:00:00,22.0,12.0,0.0,-3,80,-6,4
4,2017-01-01 04:00:00,16.0,7.0,0.0,-3,80,-6,7
...,...,...,...,...,...,...,...,...
35346,2021-01-31 19:00:00,1346.0,531.0,13.0,6,66,0,6
35347,2021-01-31 20:00:00,1298.0,589.0,7.0,6,66,0,7
35348,2021-01-31 21:00:00,1229.0,594.0,13.0,6,66,0,9
35349,2021-01-31 22:00:00,750.0,283.0,10.0,6,66,0,9
35350,2021-01-31 23:00:00,496.0,192.0,6.0,6,71,1,2

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35351 entries, 0 to 35350
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       35351 non-null  object
 1   regular        35351 non-null  float64
 2   casual         35351 non-null  float64
 3   group          35351 non-null  float64
 4   Temperature    30432 non-null  object
 5   Rel. humidity  30432 non-null  object
 6   Dew Point      30432 non-null  object
 7   Wind           30432 non-null  object
dtypes: float64(3), object(5)
memory usage: 2.2+ MB

In [54]:
df.loc[df['Temperature'].isna()]

,datetime,regular,casual,group,Temperature,Rel. humidity,Dew Point,Wind
385,2017-01-17 01:00:00,35.0,5.0,0.0,NaN,NaN,NaN,NaN
386,2017-01-17 02:00:00,34.0,4.0,0.0,NaN,NaN,NaN,NaN
387,2017-01-17 03:00:00,22.0,3.0,0.0,NaN,NaN,NaN,NaN
388,2017-01-17 04:00:00,22.0,6.0,0.0,NaN,NaN,NaN,NaN
389,2017-01-17 05:00:00,21.0,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
33797,2020-11-27 06:00:00,855.0,49.0,0.0,NaN,NaN,NaN,NaN
33804,2020-11-27 13:00:00,2166.0,447.0,3.0,NaN,NaN,NaN,NaN
33805,2020-11-27 14:00:00,2182.0,517.0,5.0,NaN,NaN,NaN,NaN
33806,2020-11-27 15:00:00,2337.0,547.0,6.0,NaN,NaN,NaN,NaN
33914,2020-12-02 03:00:00,267.0,56.0,0.0,NaN,NaN,NaN,NaN

In [77]:
df = df.loc[~df['Temperature'].isna()].reset_index(drop=True)
df

,datetime,regular,casual,group,Temperature,Rel. humidity,Dew Point,Wind
0,2017-01-01 00:00:00,63.0,13.0,1.0,-1,75,-5,9
1,2017-01-01 01:00:00,55.0,21.0,0.0,-2,80,-5,9
2,2017-01-01 02:00:00,38.0,19.0,0.0,-3,74,-7,7
3,2017-01-01 03:00:00,22.0,12.0,0.0,-3,80,-6,4
4,2017-01-01 04:00:00,16.0,7.0,0.0,-3,80,-6,7
...,...,...,...,...,...,...,...,...
30427,2021-01-31 19:00:00,1346.0,531.0,13.0,6,66,0,6
30428,2021-01-31 20:00:00,1298.0,589.0,7.0,6,66,0,7
30429,2021-01-31 21:00:00,1229.0,594.0,13.0,6,66,0,9
30430,2021-01-31 22:00:00,750.0,283.0,10.0,6,66,0,9
30431,2021-01-31 23:00:00,496.0,192.0,6.0,6,71,1,2

In [78]:
df['Temperature'].astype(float)
df['Rel. humidity'].astype(float)
df['Dew Point'].astype(float)
df['Wind'].astype(float)

0        9.0
1        9.0
2        7.0
3        4.0
4        7.0
        ...
30427    6.0
30428    7.0
30429    9.0
30430    9.0
30431    2.0
Name: Wind, Length: 30432, dtype: float64

In [79]:
df

,datetime,regular,casual,group,Temperature,Rel. humidity,Dew Point,Wind
0,2017-01-01 00:00:00,63.0,13.0,1.0,-1,75,-5,9
1,2017-01-01 01:00:00,55.0,21.0,0.0,-2,80,-5,9
2,2017-01-01 02:00:00,38.0,19.0,0.0,-3,74,-7,7
3,2017-01-01 03:00:00,22.0,12.0,0.0,-3,80,-6,4
4,2017-01-01 04:00:00,16.0,7.0,0.0,-3,80,-6,7
...,...,...,...,...,...,...,...,...
30427,2021-01-31 19:00:00,1346.0,531.0,13.0,6,66,0,6
30428,2021-01-31 20:00:00,1298.0,589.0,7.0,6,66,0,7
30429,2021-01-31 21:00:00,1229.0,594.0,13.0,6,66,0,9
30430,2021-01-31 22:00:00,750.0,283.0,10.0,6,66,0,9
30431,2021-01-31 23:00:00,496.0,192.0,6.0,6,71,1,2

In [ ]:
# 강사님 코드

In [60]:
rcg = pd.read_csv('test1_modify3.csv')
rcg

                  datetime  regular  casual  group
0      2017-01-01 00:00:00     63.0    13.0    1.0
1      2017-01-01 01:00:00     55.0    21.0    0.0
2      2017-01-01 02:00:00     38.0    19.0    0.0
3      2017-01-01 03:00:00     22.0    12.0    0.0
4      2017-01-01 04:00:00     16.0     7.0    0.0
...                    ...      ...     ...    ...
35346  2021-01-31 19:00:00   1346.0   531.0   13.0
35347  2021-01-31 20:00:00   1298.0   589.0    7.0
35348  2021-01-31 21:00:00   1229.0   594.0   13.0
35349  2021-01-31 22:00:00    750.0   283.0   10.0
35350  2021-01-31 23:00:00    496.0   192.0    6.0

[35351 rows x 4 columns]

In [ ]:
# 전부다 가져오고 전처리하기.(잘못가져오면 다시 크롤링해야하기 때문에)

In [62]:
url = 'https://freemeteo.co.uk/weather/seoul/history/daily-history/?gid=1835848&date='
date = '2020-01-01'
end = '&station=10565&language=english&country=south-korea'

one_page = pd.read_html(url + date + end)
one_page

[             Name           Weather forecast Altitiude  Population
 0           Seoul  Today | Tomorrow | 7 days       46m  10349312.0
 1             NaN  Today | Tomorrow | 7 days       12m         NaN
 2             NaN  Today | Tomorrow | 7 days       43m         NaN
 3             NaN  Today | Tomorrow | 7 days       13m         NaN
 4      Ahyon-dong  Today | Tomorrow | 7 days       27m         NaN
 5     Ahyoni-dong  Today | Tomorrow | 7 days       47m         NaN
 6    Ahyonil-tong  Today | Tomorrow | 7 days       65m         NaN
 7   Ahyonsam-dong  Today | Tomorrow | 7 days       47m         NaN
 8      Amsai-dong  Today | Tomorrow | 7 days        1m         NaN
 9     Amsail-tong  Today | Tomorrow | 7 days       18m         NaN
 10          Amsan  Today | Tomorrow | 7 days       27m         NaN
 11    Amsasa-dong  Today | Tomorrow | 7 days       26m         NaN
 12   Amsasam-dong  Today | Tomorrow | 7 days       23m         NaN
 13         An'gol  Today | Tomorrow | 7 days       58m         NaN
 14         An'gol  Today | Tomorrow | 7 days       23m         NaN
 15      Anam-dong  Today | Tomorrow | 7 days       37m         NaN
 16          Anmal  Today | Tomorrow | 7 days        5m         NaN,
                 Name           Weather forecast Forecast for altitude  \
 0          Halla-san  Today | Tomorrow | 7 days                 1950m
 1          Chiri-san  Today | Tomorrow | 7 days                 1915m
 2          Sorak-san  Today | Tomorrow | 7 days                 1708m
 3      Chiri-sanmaek  Today | Tomorrow | 7 days                 1547m
 4          Kari-bong  Today | Tomorrow | 7 days                 1519m
 5       Namdogyu-san  Today | Tomorrow | 7 days                 1508m
 6            Nogodan  Today | Tomorrow | 7 days                 1507m
 7         Muyong-san  Today | Tomorrow | 7 days                 1492m
 8      Sogyebang-san  Today | Tomorrow | 7 days                 1490m
 9        Hambaek-san  Today | Tomorrow | 7 days                 1479m
 10         Togyu-san  Today | Tomorrow | 7 days                 1469m
 11         Hwaak-san  Today | Tomorrow | 7 days                 1468m
 12      Kariwang-san  Today | Tomorrow | 7 days                 1445m
 13       Tongdae-san  Today | Tomorrow | 7 days                 1434m
 14        Manbok-tae  Today | Tomorrow | 7 days                 1433m
 15          Kaya-san  Today | Tomorrow | 7 days                 1430m
 16            An-san  Today | Tomorrow | 7 days                 1430m
 17      Chombong-san  Today | Tomorrow | 7 days                 1424m
 18       Sangwon-san  Today | Tomorrow | 7 days                 1421m
 19         Chang-san  Today | Tomorrow | 7 days                 1409m
 20       Kyebang-san  Today | Tomorrow | 7 days                 1406m
 21      Ch'ongok-san  Today | Tomorrow | 7 days                 1404m
 22     Chungwang-san  Today | Tomorrow | 7 days                 1376m
 23       Paeksok-san  Today | Tomorrow | 7 days                 1365m
 24         Kojok-tae  Today | Tomorrow | 7 days                 1354m
 25         Tut'a-san  Today | Tomorrow | 7 days                 1353m
 26        Kumwon-san  Today | Tomorrow | 7 days                 1353m
 27      T'aebaek-san  Today | Tomorrow | 7 days                 1352m
 28       Parwang-san  Today | Tomorrow | 7 days                 1349m
 29       Kuryong-san  Today | Tomorrow | 7 days                 1344m
 30         Kaein-san  Today | Tomorrow | 7 days                 1342m
 31  Sohwangbyong-san  Today | Tomorrow | 7 days                 1329m
 32          Sudo-san  Today | Tomorrow | 7 days                 1327m
 33          Odae-san  Today | Tomorrow | 7 days                 1316m
 34         Taeam-san  Today | Tomorrow | 7 days                 1314m
 35         Yaksu-san  Today | Tomorrow | 7 days                 1306m
 36       Ungbong-san  Today | Tomorrow | 7 days                 1303m
 37         Okkap-san  Today | Tomorrow | 7 days                 1302m
 38        Taedok-san  Today | Tomorrow | 7 days                 1290m
 39         Sajae-san  Today | Tomorrow | 7 days                 1284m

    Forecast for altitude.1 Forecast for altitude.2     Hotels
 0                    1532m                    862m  84 Hotels
 1                    1082m                    847m   2 Hotels
 2                    1322m                    546m   9 Hotels
 3                     847m                    516m   2 Hotels
 4                    1085m                    577m   9 Hotels
 5                     904m                    613m   0 Hotels
 6                    1103m                    555m   4 Hotels
 7                    1046m                    642m   0 Hotels
 8                     858m                    662m   6 Hotels
 9                    1159m                    632m   0 Hotels
 10                    889m                    649m   0 Hotels
 11                    905m                    473m   4 Hotels
 12                   1051m                    462m   5 Hotels
 13                    946m                    566m   6 Hotels
 14                   1103m                    644m   2 Hotels
 15                    818m                    523m   3 Hotels
 16                    798m                    562m   9 Hotels
 17                   1114m                    500m   9 Hotels
 18                    818m                    538m   7 Hotels
 19                    958m                    632m   0 Hotels
 20                    792m                    636m   6 Hotels
 21                   1040m                    456m   1 Hotels
 22                   1051m                    617m   5 Hotels
 23                    776m                    601m   5 Hotels
 24                    937m                    456m   1 Hotels
 25                    971m                    468m   1 Hotels
 26                    794m                    572m   0 Hotels
 27                    875m                    605m   0 Hotels
 28                    923m                    547m   6 Hotels
 29                    900m                    609m   0 Hotels
 30                    808m                    497m  11 Hotels
 31                    899m                    568m   6 Hotels
 32                    973m                    556m   0 Hotels
 33                    904m                    566m   7 Hotels
 34                    866m                    599m   6 Hotels
 35                    969m                    555m  15 Hotels
 36                    841m                    557m   1 Hotels
 37                    715m                    548m   7 Hotels
 38                    921m                    530m   0 Hotels
 39                    826m                    576m   4 Hotels  ,
                     Name           Weather forecast Altitiude     Hotels
 0             Panya-bong  Today | Tomorrow | 7 days     1728m   2 Hotels
 1             Chung-bong  Today | Tomorrow | 7 days     1594m   0 Hotels
 2              Piro-bong  Today | Tomorrow | 7 days     1563m   7 Hotels
 3         Taech'ong-bong  Today | Tomorrow | 7 days     1552m   9 Hotels
 4              Puso-bong  Today | Tomorrow | 7 days     1546m   0 Hotels
 5             Munsu-bong  Today | Tomorrow | 7 days     1518m   0 Hotels
 6        Kkutch'ong-bong  Today | Tomorrow | 7 days     1516m   9 Hotels
 7       Chungch'ong-bong  Today | Tomorrow | 7 days     1516m   9 Hotels
 8          Sangwang-bong  Today | Tomorrow | 7 days     1493m   7 Hotels
 9             Chung-bong  Today | Tomorrow | 7 days     1448m   4 Hotels
 10            Chuok-pong  Today | Tomorrow | 7 days     1444m  14 Hotels
 11             Piro-bong  Today | Tomorrow | 7 days     1439m   0 Hotels
 12            Chung-bong  Today | Tomorrow | 7 days     1433m   5 Hotels
 13             Turo-bong  Today | Tomorrow | 7 days     1422m  11 Hotels
 14           Kumdae-bong  Today | Tomorrow | 7 days     1418m   1 Hotels
 15  Kwittaegich'ong-bong  Today | Tomorrow | 7 days     1405m   9 Hotels
 16       Hwangch'ol-bong  Today | Tomorrow | 7 days     1384m   9 Hotels
 17               Ha-bong  Today | Tomorrow | 7 days     1380m   5 Hotels
 18            Undae-bong  Today | Tomorrow | 7 days     1365m   0 Hotels
 19          Horyong-bong  Today | Tomorrow | 7 days     1355m   6 Hotels
 20         Changgun-bong  Today | Tomorrow | 7 days     1352m   0 Hotels
 21            Samdu-bong  Today | Tomorrow | 7 days     1343m   2 Hotels
 22             Sara-orum  Today | Tomorrow | 7 days     1338m  84 Hotels
 23             Noin-bong  Today | Tomorrow | 7 days     1338m   6 Hotels
 24           Suttol-bong  Today | Tomorrow | 7 days     1327m  11 Hotels
 25            Tanji-bong  Today | Tomorrow | 7 days     1326m   0 Hotels
 26         Soch'ong-bong  Today | Tomorrow | 7 days     1322m   9 Hotels
 27            Tosol-bong  Today | Tomorrow | 7 days     1314m   0 Hotels
 28          Hyangno-bong  Today | Tomorrow | 7 days     1293m   9 Hotels
 29           Manwol-bong  Today | Tomorrow | 7 days     1281m  14 Hotels
 30            Oktol-bong  Today | Tomorrow | 7 days     1241m   0 Hotels
 31          Paeksok-pong  Today | Tomorrow | 7 days     1238m   5 Hotels
 32             Turu-bong  Today | Tomorrow | 7 days     1225m   6 Hotels
 33          Songnor-orum  Today | Tomorrow | 7 days     1215m  84 Hotels
 34        Maenghyon-bong  Today | Tomorrow | 7 days     1214m   6 Hotels
 35           Mangji-bong  Today | Tomorrow | 7 days     1210m   1 Hotels
 36            Ch'il-bong  Today | Tomorrow | 7 days     1196m   0 Hotels
 37              Tol-orum  Today | Tomorrow | 7 days     1193m  84 Hotels
 38             Tuwi-bong  Today | Tomorrow | 7 days     1192m   0 Hotels
 39            Chogo-bong  Today | Tomorrow | 7 days     1189m   7 Hotels,
          Name                     Weather forecast Base altitude Top altitude  \
 0  Ch'onmasan  Today | Tomorrow | 7 days | Weekend          200m         400m
 1    Daemyung  Today | Tomorrow | 7 days | Weekend          600m        1858m
 2     Konjiam  Today | Tomorrow | 7 days | Weekend          188m         514m
 3        Muju  Today | Tomorrow | 7 days | Weekend          750m        1215m
 4   Yongpyong  Today | Tomorrow | 7 days | Weekend         1150m        1858m

        Hotels
 0  597 Hotels
 1    5 Hotels
 2  292 Hotels
 3    0 Hotels
 4    5 Hotels  ,
                              Name                     Weather forecast  \
 0                            Asan  Today | Tomorrow | 7 days | Weekend
 1                         Bucheon  Today | Tomorrow | 7 days | Weekend
 2                           Busan  Today | Tomorrow | 7 days | Weekend
 3                      Changhowon  Today | Tomorrow | 7 days | Weekend
 4                        Changwon  Today | Tomorrow | 7 days | Weekend
 5                        Cheongju  Today | Tomorrow | 7 days | Weekend
 6                       Chuncheon  Today | Tomorrow | 7 days | Weekend
 7                         Chungju  Today | Tomorrow | 7 days | Weekend
 8                    Chungnang-gu  Today | Tomorrow | 7 days | Weekend
 9                           Daegu  Today | Tomorrow | 7 days | Weekend
 10                        Dongtan  Today | Tomorrow | 7 days | Weekend
 11                         Gimhae  Today | Tomorrow | 7 days | Weekend
 12                           Gumi  Today | Tomorrow | 7 days | Weekend
 13                       Gyeongju  Today | Tomorrow | 7 days | Weekend
 14                       Haeundae  Today | Tomorrow | 7 days | Weekend
 15                         Icheon  Today | Tomorrow | 7 days | Weekend
 16                        Incheon  Today | Tomorrow | 7 days | Weekend
 17  Incheon International Airport  Today | Tomorrow | 7 days | Weekend
 18                           Jeju  Today | Tomorrow | 7 days | Weekend
 19                           Jeju  Today | Tomorrow | 7 days | Weekend
 20                         Jeonju  Today | Tomorrow | 7 days | Weekend
 21                      Mapo-dong  Today | Tomorrow | 7 days | Weekend
 22                       Mia-dong  Today | Tomorrow | 7 days | Weekend
 23                          Mokpo  Today | Tomorrow | 7 days | Weekend
 24                        Omin-ni  Today | Tomorrow | 7 days | Weekend
 25                         Pohang  Today | Tomorrow | 7 days | Weekend
 26                    Pyeongchang  Today | Tomorrow | 7 days | Weekend
 27                       Seogwipo  Today | Tomorrow | 7 days | Weekend
 28                       Seongnam  Today | Tomorrow | 7 days | Weekend
 29                    Sihung-dong  Today | Tomorrow | 7 days | Weekend
 30                    Sodaemun-gu  Today | Tomorrow | 7 days | Weekend
 31                     Songbuk-gu  Today | Tomorrow | 7 days | Weekend
 32                       Songdong  Today | Tomorrow | 7 days | Weekend
 33                     Songnam-si  Today | Tomorrow | 7 days | Weekend
 34                     Tongdaemun  Today | Tomorrow | 7 days | Weekend
 35                         Tuksom  Today | Tomorrow | 7 days | Weekend
 36                       Yangyang  Today | Tomorrow | 7 days | Weekend
 37                          Yeosu  Today | Tomorrow | 7 days | Weekend
 38                         Yongin  Today | Tomorrow | 7 days | Weekend
 39                     Yongsan-gu  Today | Tomorrow | 7 days | Weekend

    Altitiude  Attractions      Hotels
 0        15m            3   10 Hotels
 1         0m           86  627 Hotels
 2         0m           31  125 Hotels
 3        66m            1    4 Hotels
 4        48m            7    7 Hotels
 5         0m           25   14 Hotels
 6         0m            3    5 Hotels
 7         0m            1    2 Hotels
 8         0m           80  580 Hotels
 9         0m           10   13 Hotels
 10        0m           31  173 Hotels
 11        0m           32  126 Hotels
 12        0m            7   12 Hotels
 13        0m           13   35 Hotels
 14       16m           28  123 Hotels
 15        0m            6   42 Hotels
 16        0m           28  288 Hotels
 17        7m           18  112 Hotels
 18        0m           25   81 Hotels
 19        0m           24   80 Hotels
 20        0m            8    0 Hotels
 21        0m           86  612 Hotels
 22       37m           81  578 Hotels
 23        0m            5    0 Hotels
 24        0m           86  601 Hotels
 25        0m           11   32 Hotels
 26        0m            4    5 Hotels
 27       65m           23   78 Hotels
 28        0m           76  588 Hotels
 29       28m           87  620 Hotels
 30        0m           86  610 Hotels
 31        0m           85  598 Hotels
 32       23m           83  591 Hotels
 33        0m           77  573 Hotels
 34        0m           85  599 Hotels
 35        0m           78  585 Hotels
 36       11m            8   10 Hotels
 37        0m            2    5 Hotels
 38       90m           35  207 Hotels
 39        0m           87  603 Hotels  ,
    Station name  Country name  latitude  longitude  Altitude  Distance  Date
 0           NaN           NaN       NaN        NaN       NaN       NaN   NaN,
      Time Temperature Relative Temperature          Wind  Wind Gust  \
 0   00:00        -6°C                 -6°C   200° 2 Km/h        NaN
 1   01:00        -5°C                 -8°C   170° 6 Km/h        NaN
 2   02:00        -5°C                 -8°C   160° 7 Km/h        NaN
 3   03:00        -5°C                -10°C  160° 11 Km/h        NaN
 4   04:00        -6°C                -11°C  160° 11 Km/h        NaN
 5   05:00        -5°C                -10°C  130° 11 Km/h        NaN
 6   06:00        -5°C                 -9°C   150° 9 Km/h        NaN
 7   07:00        -4°C                 -6°C   170° 6 Km/h        NaN
 8   08:00        -3°C                 -6°C   130° 7 Km/h        NaN
 9   09:00        -3°C                 -6°C   160° 7 Km/h        NaN
 10  10:00        -2°C                 -4°C    80° 6 Km/h        NaN
 11  11:00        -2°C                 -5°C   130° 7 Km/h        NaN
 12  12:00        -1°C                 -4°C   100° 9 Km/h        NaN
 13  13:00         0°C                 -2°C    80° 6 Km/h        NaN
 14  14:00         1°C                 -1°C   100° 6 Km/h        NaN
 15  15:00         2°C                  2°C   230° 2 Km/h        NaN
 16  16:00         2°C                  2°C   150° 4 Km/h        NaN
 17  17:00         1°C                  1°C    30° 2 Km/h        NaN
 18  18:00         1°C                 -1°C   280° 6 Km/h        NaN
 19  19:00         1°C                  1°C   330° 4 Km/h        NaN
 20  20:00         0°C                 -2°C   340° 6 Km/h        NaN
 21  21:00         0°C                  0°C   350° 2 Km/h        NaN
 22  22:00         0°C                  0°C    10° 2 Km/h        NaN
 23  23:00         0°C                  0°C   350° 2 Km/h        NaN

    Rel. humidity Dew Point  Pressure  Icon  \
 0            68%     -11°C  1033.0mb   NaN
 1            58%     -12°C  1033.0mb   NaN
 2            63%     -11°C  1032.0mb   NaN
 3            63%     -11°C  1032.0mb   NaN
 4            74%     -10°C  1032.0mb   NaN
 5            68%     -10°C  1032.0mb   NaN
 6            68%     -10°C  1032.0mb   NaN
 7            69%      -9°C  1032.0mb   NaN
 8            69%      -8°C  1032.0mb   NaN
 9            69%      -8°C  1033.0mb   NaN
 10           74%      -6°C  1033.0mb   NaN
 11           80%      -5°C  1033.0mb   NaN
 12           80%      -4°C  1032.0mb   NaN
 13           75%      -4°C  1031.0mb   NaN
 14           70%      -4°C  1031.0mb   NaN
 15           65%      -4°C  1031.0mb   NaN
 16           65%      -4°C  1031.0mb   NaN
 17           70%      -4°C  1031.0mb   NaN
 18           70%      -4°C  1031.0mb   NaN
 19           75%      -3°C  1031.0mb   NaN
 20           80%      -3°C  1031.0mb   NaN
 21           80%      -3°C  1031.0mb   NaN
 22           80%      -3°C  1031.0mb   NaN
 23           80%      -3°C  1031.0mb   NaN

                                    DescriptionDetails
 0   document.write(Icons.GetShortDescription(26, '...
 1   document.write(Icons.GetShortDescription(26, '...
 2   document.write(Icons.GetShortDescription(26, '...
 3   document.write(Icons.GetShortDescription(26, '...
 4   document.write(Icons.GetShortDescription(26, '...
 5   document.write(Icons.GetShortDescription(26, '...
 6   document.write(Icons.GetShortDescription(26, '...
 7   document.write(Icons.GetShortDescription(26, '...
 8   document.write(Icons.GetShortDescription(26, '...
 9   document.write(Icons.GetShortDescription(3, 'C...
 10  document.write(Icons.GetShortDescription(26, '...
 11  document.write(Icons.GetShortDescription(26, '...
 12  document.write(Icons.GetShortDescription(3, 'C...
 13  document.write(Icons.GetShortDescription(3, 'C...
 14  document.write(Icons.GetShortDescription(3, 'C...
 15  document.write(Icons.GetShortDescription(3, 'C...
 16  document.write(Icons.GetShortDescription(3, 'C...
 17  document.write(Icons.GetShortDescription(3, 'C...
 18  document.write(Icons.GetShortDescription(3, 'C...
 19  document.write(Icons.GetShortDescription(3, 'C...
 20  document.write(Icons.GetShortDescription(3, 'C...
 21  document.write(Icons.GetShortDescription(3, 'C...
 22  document.write(Icons.GetShortDescription(4, 'C...
 23  document.write(Icons.GetShortDescription(4, 'C...  ,
                  0      1        2       3          4               5
 0  Hourly Forecast  Today  Weekend  7 days  Meteogram  Live Satellite,
                  0      1        2       3          4               5
 0  Hourly Forecast  Today  Weekend  7 days  Meteogram  Live Satellite]

In [65]:
weather_df = one_page[6] #7번째
weather_df['date'] = date
weather_df.head()

,Time,Temperature,Relative Temperature,Wind,Wind Gust,Rel. humidity,Dew Point,Pressure,Icon,DescriptionDetails,date
0,00:00,-6°C,-6°C,200° 2 Km/h,NaN,68%,-11°C,1033.0mb,NaN,"document.write(Icons.GetShortDescription(26, '...",2020-01-01
1,01:00,-5°C,-8°C,170° 6 Km/h,NaN,58%,-12°C,1033.0mb,NaN,"document.write(Icons.GetShortDescription(26, '...",2020-01-01
2,02:00,-5°C,-8°C,160° 7 Km/h,NaN,63%,-11°C,1032.0mb,NaN,"document.write(Icons.GetShortDescription(26, '...",2020-01-01
3,03:00,-5°C,-10°C,160° 11 Km/h,NaN,63%,-11°C,1032.0mb,NaN,"document.write(Icons.GetShortDescription(26, '...",2020-01-01
4,04:00,-6°C,-11°C,160° 11 Km/h,NaN,74%,-10°C,1032.0mb,NaN,"document.write(Icons.GetShortDescription(26, '...",2020-01-01

In [66]:
def save_weather(date):
    url = 'https://freemeteo.co.uk/weather/seoul/history/daily-history/?gid=1835848&date='
    end = '&station=10565&language=english&country=south-korea'
    
    one_page = pd.read_html(url + date + end)

    weather_df = one_page[6] #7번째
    weather_df['date'] = date
    weather_df.to_csv(date + '.csv', index=False)

In [68]:
for date in pd.date_range('2017-01-01', '2017-01-10'):
    time.sleep(2) # 필수
    print(str(date)[:10])

2017-01-01
2017-01-02
2017-01-03
2017-01-04
2017-01-05
2017-01-06
2017-01-07
2017-01-08
2017-01-09
2017-01-10

In [69]:
from glob import glob

In [70]:
path = 'C:/Users/twas0/test/weather'
pd.read_csv(glob(path + '/*.csv')[0]).head()

,Time,Temperature,Relative Temperature,Wind,Wind Gust,Rel. humidity,Dew Point,Pressure,Icon,DescriptionDetails,date
0,00:00,-1°C,-4°C,150°9 Km/h,NaN,75%,-5°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
1,01:00,-2°C,-5°C,160°9 Km/h,NaN,80%,-5°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
2,02:00,-3°C,-6°C,160°7 Km/h,NaN,74%,-7°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
3,03:00,-3°C,-3°C,170°4 Km/h,NaN,80%,-6°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
4,04:00,-3°C,-6°C,160°7 Km/h,NaN,80%,-6°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01

In [71]:
weather_ls = []

for weather in glob(path + '/*.csv'):
    weather_ls.append(pd.read_csv(weather))

all_weather = pd.concat(weather_ls)
all_weather.shape

(32513, 11)

In [73]:
all_weather.head()

,Time,Temperature,Relative Temperature,Wind,Wind Gust,Rel. humidity,Dew Point,Pressure,Icon,DescriptionDetails,date
0,00:00,-1°C,-4°C,150°9 Km/h,NaN,75%,-5°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
1,01:00,-2°C,-5°C,160°9 Km/h,NaN,80%,-5°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
2,02:00,-3°C,-6°C,160°7 Km/h,NaN,74%,-7°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
3,03:00,-3°C,-3°C,170°4 Km/h,NaN,80%,-6°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01
4,04:00,-3°C,-6°C,160°7 Km/h,NaN,80%,-6°C,1029.0mb,NaN,"document.write(Icons.GetShortDescription(2, 'C...",2017-01-01

#### all_weather 수정사항
- Time + date로 datetime 생성하기
- 필요한 column(datetime, Temparature, Wind, humidity, Dew Point)만 선별
- 필요한 column을 수치형으로 변환

In [80]:
# Time 길이가 같은지 확인
set(all_weather['Time'].apply(lambda x: len(x)))

{5}

In [82]:
set(all_weather['Time'].apply(lambda x: x[:2]))

{'00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23'}

In [84]:
all_weather['Time'] = all_weather['Time'].apply(lambda x: x[:2])
all_weather['datetime'] = all_weather['date'] + ' ' + all_weather['Time'] + ':00:00'
all_weather[['datetime']].head()

              datetime
0  2017-01-01 00:00:00
1  2017-01-01 01:00:00
2  2017-01-01 02:00:00
3  2017-01-01 03:00:00
4  2017-01-01 04:00:00

In [86]:
all_weather.columns

Index(['Time', 'Temperature', 'Relative Temperature', 'Wind', 'Wind Gust',
       'Rel. humidity', 'Dew Point', 'Pressure', 'Icon', 'DescriptionDetails',
       'date', 'datetime'],
      dtype='object')

In [87]:
all_weather[['Temperature', 'Dew Point']]

   Temperature Dew Point
0         -1°C      -5°C
1         -2°C      -5°C
2         -3°C      -7°C
3         -3°C      -6°C
4         -3°C      -6°C
..         ...       ...
19         6°C       0°C
20         6°C       0°C
21         6°C       0°C
22         6°C       0°C
23         6°C       1°C

[32513 rows x 2 columns]

In [88]:
all_weather['temp'] = all_weather['Temperature'].apply(lambda x: int(x[:-2]))
all_weather['dew'] = all_weather['Dew Point'].apply(lambda x: int(x[:-2]))
all_weather[['temp', 'dew']]

    temp  dew
0     -1   -5
1     -2   -5
2     -3   -7
3     -3   -6
4     -3   -6
..   ...  ...
19     6    0
20     6    0
21     6    0
22     6    0
23     6    1

[32513 rows x 2 columns]

In [90]:
set(all_weather['Rel. humidity'].apply(lambda x: x[-1:]))

{'%'}

In [91]:
all_weather['humid'] = all_weather['Rel. humidity'].apply(lambda x: int(x[:-1]))
all_weather[['humid']]

    humid
0      75
1      80
2      74
3      80
4      80
..    ...
19     66
20     66
21     66
22     66
23     71

[32513 rows x 1 columns]

In [93]:
all_weather['Wind']

# 왜 풍향은 안가져가고 풍속만 가져갈까 ?
# 서울시 따릉이 고객들이 한방향으로 간다면 풍향이 의미가 있지만, 사방팔방 가는 곳이 다르기 때문에 불필요하다고 생각함
# 한방향으로 간다면 풍향에 따라 뒤에서 바람이 밀 수도 있고, 앞에서 막을 수도 있기 때문에 유의하지만 지금은 X

0     150°9 Km/h
1     160°9 Km/h
2     160°7 Km/h
3     170°4 Km/h
4     160°7 Km/h
         ...
19    150°6 Km/h
20    150°7 Km/h
21    130°9 Km/h
22    160°9 Km/h
23     90°2 Km/h
Name: Wind, Length: 32513, dtype: object

In [94]:
set(all_weather['Wind'].apply(lambda x: x[-4:]))

# 바림이 없는 경우 = Calm

{'Calm', 'Km/h'}

In [98]:
all_weather['Wind'] = all_weather['Wind'].apply(lambda x: x.replace('Calm', '000°0 Km/h'))
set(all_weather['Wind'].apply(lambda x: x[-4:]))

{'Km/h'}

In [99]:
all_weather['windspeed'] = all_weather['Wind'].apply(lambda x: int(x.split(' ')[0].split('°')[1]))
all_weather[['windspeed']]

    windspeed
0           9
1           9
2           7
3           4
4           7
..        ...
19          6
20          7
21          9
22          9
23          2

[32513 rows x 1 columns]

In [100]:
all_weather.columns

Index(['Time', 'Temperature', 'Relative Temperature', 'Wind', 'Wind Gust',
       'Rel. humidity', 'Dew Point', 'Pressure', 'Icon', 'DescriptionDetails',
       'date', 'datetime', 'temp', 'dew', 'humid', 'windspeed'],
      dtype='object')

In [102]:
interested = ['datetime', 'temp', 'dew', 'humid', 'windspeed']
all_weather[interested].to_csv('weather_modify.csv', index=False)

In [106]:
rcg

                  datetime  regular  casual  group
0      2017-01-01 00:00:00     63.0    13.0    1.0
1      2017-01-01 01:00:00     55.0    21.0    0.0
2      2017-01-01 02:00:00     38.0    19.0    0.0
3      2017-01-01 03:00:00     22.0    12.0    0.0
4      2017-01-01 04:00:00     16.0     7.0    0.0
...                    ...      ...     ...    ...
35346  2021-01-31 19:00:00   1346.0   531.0   13.0
35347  2021-01-31 20:00:00   1298.0   589.0    7.0
35348  2021-01-31 21:00:00   1229.0   594.0   13.0
35349  2021-01-31 22:00:00    750.0   283.0   10.0
35350  2021-01-31 23:00:00    496.0   192.0    6.0

[35351 rows x 4 columns]

In [107]:
weather = pd.read_csv('weather_modify.csv')
weather

                  datetime  temp  dew  humid  windspeed
0      2017-01-01 00:00:00    -1   -5     75          9
1      2017-01-01 01:00:00    -2   -5     80          9
2      2017-01-01 02:00:00    -3   -7     74          7
3      2017-01-01 03:00:00    -3   -6     80          4
4      2017-01-01 04:00:00    -3   -6     80          7
...                    ...   ...  ...    ...        ...
32508  2021-01-31 19:00:00     6    0     66          6
32509  2021-01-31 20:00:00     6    0     66          7
32510  2021-01-31 21:00:00     6    0     66          9
32511  2021-01-31 22:00:00     6    0     66          9
32512  2021-01-31 23:00:00     6    1     71          2

[32513 rows x 5 columns]

In [214]:
pd.merge(rcg, weather, how='inner').sort_values(by = 'datetime').to_csv('test1_modify4.csv', index=False)

In [215]:
df = pd.read_csv('test1_modify4.csv')
print(df.shape)
df.head()

(32103, 8)

              datetime  regular  casual  group  temp  dew  humid  windspeed
0  2017-01-01 00:00:00     63.0    13.0    1.0    -1   -5     75          9
1  2017-01-01 01:00:00     55.0    21.0    0.0    -2   -5     80          9
2  2017-01-01 02:00:00     38.0    19.0    0.0    -3   -7     74          7
3  2017-01-01 03:00:00     22.0    12.0    0.0    -3   -6     80          4
4  2017-01-01 04:00:00     16.0     7.0    0.0    -3   -6     80          7

In [227]:
# 중복된 행 확인
duplicates = df[df['datetime'].duplicated(keep=False)]
duplicates

# datetime을 groupby해서 평균내서 중복처리

,datetime,regular,casual,group,temp,dew,humid,windspeed
33,2017-01-02 09:00:00,138.0,6.0,0.0,5,2,81,9
34,2017-01-02 09:00:00,138.0,6.0,0.0,6,2,76,9
45,2017-01-02 20:00:00,171.0,13.0,2.0,2,-1,81,7
46,2017-01-02 20:00:00,171.0,13.0,2.0,4,0,75,7
56,2017-01-03 06:00:00,74.0,1.0,0.0,-5,-9,74,2
...,...,...,...,...,...,...,...,...
32013,2021-01-28 09:00:00,1217.0,125.0,2.0,-1,-3,86,19
32014,2021-01-28 10:00:00,133.0,11.0,0.0,-1,-1,100,19
32015,2021-01-28 10:00:00,133.0,11.0,0.0,0,-1,93,17
32016,2021-01-28 10:00:00,133.0,11.0,0.0,1,0,93,17
32017,2021-01-28 10:00:00,133.0,11.0,0.0,1,0,93,22

In [232]:
df.groupby('datetime').agg(np.mean)

C:\Users\twas0\AppData\Local\Temp\ipykernel_22036\1981455255.py:1: FutureWarning: The provided callable <function mean at 0x000001EC58A26FC0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('datetime').agg(np.mean)

                     regular  casual  group  temp  dew  humid  windspeed
datetime
2017-01-01 00:00:00     63.0    13.0    1.0  -1.0 -5.0   75.0        9.0
2017-01-01 01:00:00     55.0    21.0    0.0  -2.0 -5.0   80.0        9.0
2017-01-01 02:00:00     38.0    19.0    0.0  -3.0 -7.0   74.0        7.0
2017-01-01 03:00:00     22.0    12.0    0.0  -3.0 -6.0   80.0        4.0
2017-01-01 04:00:00     16.0     7.0    0.0  -3.0 -6.0   80.0        7.0
...                      ...     ...    ...   ...  ...    ...        ...
2021-01-31 19:00:00   1346.0   531.0   13.0   6.0  0.0   66.0        6.0
2021-01-31 20:00:00   1298.0   589.0    7.0   6.0  0.0   66.0        7.0
2021-01-31 21:00:00   1229.0   594.0   13.0   6.0  0.0   66.0        9.0
2021-01-31 22:00:00    750.0   283.0   10.0   6.0  0.0   66.0        9.0
2021-01-31 23:00:00    496.0   192.0    6.0   6.0  1.0   71.0        2.0

[30437 rows x 7 columns]

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32103 entries, 0 to 32102
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   32103 non-null  object
 1   regular    32103 non-null  float64
 2   casual     32103 non-null  float64
 3   group      32103 non-null  float64
 4   temp       32103 non-null  int64
 5   dew        32103 non-null  int64
 6   humid      32103 non-null  int64
 7   windspeed  32103 non-null  int64
dtypes: float64(3), int64(4), object(1)
memory usage: 2.0+ MB